/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public final class ThostTeResumeType {
	public final static ThostTeResumeType THOST_TERT_RESTART = new ThostTeResumeType(
			"THOST_TERT_RESTART", 0);
	public final static ThostTeResumeType THOST_TERT_RESUME = new ThostTeResumeType(
			"THOST_TERT_RESUME");
	public final static ThostTeResumeType THOST_TERT_QUICK = new ThostTeResumeType(
			"THOST_TERT_QUICK");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static ThostTeResumeType swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + ThostTeResumeType.class
				+ " with value " + swigValue);
	}

	private ThostTeResumeType(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private ThostTeResumeType(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private ThostTeResumeType(String swigName, ThostTeResumeType swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static ThostTeResumeType[] swigValues = { THOST_TERT_RESTART,
			THOST_TERT_RESUME, THOST_TERT_QUICK };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
