/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcRspAuthenticateField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcRspAuthenticateField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcRspAuthenticateField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcRspAuthenticateField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcRspAuthenticateField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcRspAuthenticateField_BrokerID_get(swigCPtr,
				this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcRspAuthenticateField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcRspAuthenticateField_UserID_get(swigCPtr, this);
	}

	public void setUserProductInfo(String value) {
		CtpJNI.CThostFtdcRspAuthenticateField_UserProductInfo_set(swigCPtr,
				this, value);
	}

	public String getUserProductInfo() {
		return CtpJNI.CThostFtdcRspAuthenticateField_UserProductInfo_get(
				swigCPtr, this);
	}

	public CThostFtdcRspAuthenticateField() {
		this(CtpJNI.new_CThostFtdcRspAuthenticateField(), true);
	}

}
