/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcReqChangeAccountField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcReqChangeAccountField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcReqChangeAccountField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcReqChangeAccountField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_TradeCode_set(swigCPtr, this,
				value);
	}

	public String getTradeCode() {
		return CtpJNI.CThostFtdcReqChangeAccountField_TradeCode_get(swigCPtr,
				this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BankID_set(swigCPtr, this, value);
	}

	public String getBankID() {
		return CtpJNI
				.CThostFtdcReqChangeAccountField_BankID_get(swigCPtr, this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BankBranchID_set(swigCPtr, this,
				value);
	}

	public String getBankBranchID() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BankBranchID_get(
				swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BrokerID_get(swigCPtr,
				this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BrokerBranchID_set(swigCPtr,
				this, value);
	}

	public String getBrokerBranchID() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BrokerBranchID_get(
				swigCPtr, this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_TradeDate_set(swigCPtr, this,
				value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcReqChangeAccountField_TradeDate_get(swigCPtr,
				this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_TradeTime_set(swigCPtr, this,
				value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcReqChangeAccountField_TradeTime_get(swigCPtr,
				this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BankSerial_set(swigCPtr, this,
				value);
	}

	public String getBankSerial() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BankSerial_get(swigCPtr,
				this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_TradingDay_set(swigCPtr, this,
				value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcReqChangeAccountField_TradingDay_get(swigCPtr,
				this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcReqChangeAccountField_PlateSerial_set(swigCPtr, this,
				value);
	}

	public int getPlateSerial() {
		return CtpJNI.CThostFtdcReqChangeAccountField_PlateSerial_get(swigCPtr,
				this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_LastFragment_set(swigCPtr, this,
				value);
	}

	public char getLastFragment() {
		return CtpJNI.CThostFtdcReqChangeAccountField_LastFragment_get(
				swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcReqChangeAccountField_SessionID_set(swigCPtr, this,
				value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcReqChangeAccountField_SessionID_get(swigCPtr,
				this);
	}

	public void setCustomerName(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_CustomerName_set(swigCPtr, this,
				value);
	}

	public String getCustomerName() {
		return CtpJNI.CThostFtdcReqChangeAccountField_CustomerName_get(
				swigCPtr, this);
	}

	public void setIdCardType(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_IdCardType_set(swigCPtr, this,
				value);
	}

	public char getIdCardType() {
		return CtpJNI.CThostFtdcReqChangeAccountField_IdCardType_get(swigCPtr,
				this);
	}

	public void setIdentifiedCardNo(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_IdentifiedCardNo_set(swigCPtr,
				this, value);
	}

	public String getIdentifiedCardNo() {
		return CtpJNI.CThostFtdcReqChangeAccountField_IdentifiedCardNo_get(
				swigCPtr, this);
	}

	public void setGender(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_Gender_set(swigCPtr, this, value);
	}

	public char getGender() {
		return CtpJNI
				.CThostFtdcReqChangeAccountField_Gender_get(swigCPtr, this);
	}

	public void setCountryCode(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_CountryCode_set(swigCPtr, this,
				value);
	}

	public String getCountryCode() {
		return CtpJNI.CThostFtdcReqChangeAccountField_CountryCode_get(swigCPtr,
				this);
	}

	public void setCustType(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_CustType_set(swigCPtr, this,
				value);
	}

	public char getCustType() {
		return CtpJNI.CThostFtdcReqChangeAccountField_CustType_get(swigCPtr,
				this);
	}

	public void setAddress(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_Address_set(swigCPtr, this,
				value);
	}

	public String getAddress() {
		return CtpJNI.CThostFtdcReqChangeAccountField_Address_get(swigCPtr,
				this);
	}

	public void setZipCode(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_ZipCode_set(swigCPtr, this,
				value);
	}

	public String getZipCode() {
		return CtpJNI.CThostFtdcReqChangeAccountField_ZipCode_get(swigCPtr,
				this);
	}

	public void setTelephone(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_Telephone_set(swigCPtr, this,
				value);
	}

	public String getTelephone() {
		return CtpJNI.CThostFtdcReqChangeAccountField_Telephone_get(swigCPtr,
				this);
	}

	public void setMobilePhone(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_MobilePhone_set(swigCPtr, this,
				value);
	}

	public String getMobilePhone() {
		return CtpJNI.CThostFtdcReqChangeAccountField_MobilePhone_get(swigCPtr,
				this);
	}

	public void setFax(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_Fax_set(swigCPtr, this, value);
	}

	public String getFax() {
		return CtpJNI.CThostFtdcReqChangeAccountField_Fax_get(swigCPtr, this);
	}

	public void setEMail(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_EMail_set(swigCPtr, this, value);
	}

	public String getEMail() {
		return CtpJNI.CThostFtdcReqChangeAccountField_EMail_get(swigCPtr, this);
	}

	public void setMoneyAccountStatus(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_MoneyAccountStatus_set(swigCPtr,
				this, value);
	}

	public char getMoneyAccountStatus() {
		return CtpJNI.CThostFtdcReqChangeAccountField_MoneyAccountStatus_get(
				swigCPtr, this);
	}

	public void setBankAccount(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BankAccount_set(swigCPtr, this,
				value);
	}

	public String getBankAccount() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BankAccount_get(swigCPtr,
				this);
	}

	public void setBankPassWord(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BankPassWord_set(swigCPtr, this,
				value);
	}

	public String getBankPassWord() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BankPassWord_get(
				swigCPtr, this);
	}

	public void setNewBankAccount(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_NewBankAccount_set(swigCPtr,
				this, value);
	}

	public String getNewBankAccount() {
		return CtpJNI.CThostFtdcReqChangeAccountField_NewBankAccount_get(
				swigCPtr, this);
	}

	public void setNewBankPassWord(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_NewBankPassWord_set(swigCPtr,
				this, value);
	}

	public String getNewBankPassWord() {
		return CtpJNI.CThostFtdcReqChangeAccountField_NewBankPassWord_get(
				swigCPtr, this);
	}

	public void setAccountID(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_AccountID_set(swigCPtr, this,
				value);
	}

	public String getAccountID() {
		return CtpJNI.CThostFtdcReqChangeAccountField_AccountID_get(swigCPtr,
				this);
	}

	public void setPassword(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_Password_set(swigCPtr, this,
				value);
	}

	public String getPassword() {
		return CtpJNI.CThostFtdcReqChangeAccountField_Password_get(swigCPtr,
				this);
	}

	public void setBankAccType(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BankAccType_set(swigCPtr, this,
				value);
	}

	public char getBankAccType() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BankAccType_get(swigCPtr,
				this);
	}

	public void setInstallID(int value) {
		CtpJNI.CThostFtdcReqChangeAccountField_InstallID_set(swigCPtr, this,
				value);
	}

	public int getInstallID() {
		return CtpJNI.CThostFtdcReqChangeAccountField_InstallID_get(swigCPtr,
				this);
	}

	public void setVerifyCertNoFlag(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_VerifyCertNoFlag_set(swigCPtr,
				this, value);
	}

	public char getVerifyCertNoFlag() {
		return CtpJNI.CThostFtdcReqChangeAccountField_VerifyCertNoFlag_get(
				swigCPtr, this);
	}

	public void setCurrencyID(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_CurrencyID_set(swigCPtr, this,
				value);
	}

	public String getCurrencyID() {
		return CtpJNI.CThostFtdcReqChangeAccountField_CurrencyID_get(swigCPtr,
				this);
	}

	public void setBrokerIDByBank(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BrokerIDByBank_set(swigCPtr,
				this, value);
	}

	public String getBrokerIDByBank() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BrokerIDByBank_get(
				swigCPtr, this);
	}

	public void setBankPwdFlag(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_BankPwdFlag_set(swigCPtr, this,
				value);
	}

	public char getBankPwdFlag() {
		return CtpJNI.CThostFtdcReqChangeAccountField_BankPwdFlag_get(swigCPtr,
				this);
	}

	public void setSecuPwdFlag(char value) {
		CtpJNI.CThostFtdcReqChangeAccountField_SecuPwdFlag_set(swigCPtr, this,
				value);
	}

	public char getSecuPwdFlag() {
		return CtpJNI.CThostFtdcReqChangeAccountField_SecuPwdFlag_get(swigCPtr,
				this);
	}

	public void setTID(int value) {
		CtpJNI.CThostFtdcReqChangeAccountField_TID_set(swigCPtr, this, value);
	}

	public int getTID() {
		return CtpJNI.CThostFtdcReqChangeAccountField_TID_get(swigCPtr, this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcReqChangeAccountField_Digest_set(swigCPtr, this, value);
	}

	public String getDigest() {
		return CtpJNI
				.CThostFtdcReqChangeAccountField_Digest_get(swigCPtr, this);
	}

	public CThostFtdcReqChangeAccountField() {
		this(CtpJNI.new_CThostFtdcReqChangeAccountField(), true);
	}

}
