/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcLinkManField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcLinkManField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcLinkManField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcLinkManField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcLinkManField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcLinkManField_BrokerID_get(swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcLinkManField_InvestorID_set(swigCPtr, this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcLinkManField_InvestorID_get(swigCPtr, this);
	}

	public void setPersonType(char value) {
		CtpJNI.CThostFtdcLinkManField_PersonType_set(swigCPtr, this, value);
	}

	public char getPersonType() {
		return CtpJNI.CThostFtdcLinkManField_PersonType_get(swigCPtr, this);
	}

	public void setIdentifiedCardType(char value) {
		CtpJNI.CThostFtdcLinkManField_IdentifiedCardType_set(swigCPtr, this,
				value);
	}

	public char getIdentifiedCardType() {
		return CtpJNI.CThostFtdcLinkManField_IdentifiedCardType_get(swigCPtr,
				this);
	}

	public void setIdentifiedCardNo(String value) {
		CtpJNI.CThostFtdcLinkManField_IdentifiedCardNo_set(swigCPtr, this,
				value);
	}

	public String getIdentifiedCardNo() {
		return CtpJNI.CThostFtdcLinkManField_IdentifiedCardNo_get(swigCPtr,
				this);
	}

	public void setPersonName(String value) {
		CtpJNI.CThostFtdcLinkManField_PersonName_set(swigCPtr, this, value);
	}

	public String getPersonName() {
		return CtpJNI.CThostFtdcLinkManField_PersonName_get(swigCPtr, this);
	}

	public void setTelephone(String value) {
		CtpJNI.CThostFtdcLinkManField_Telephone_set(swigCPtr, this, value);
	}

	public String getTelephone() {
		return CtpJNI.CThostFtdcLinkManField_Telephone_get(swigCPtr, this);
	}

	public void setAddress(String value) {
		CtpJNI.CThostFtdcLinkManField_Address_set(swigCPtr, this, value);
	}

	public String getAddress() {
		return CtpJNI.CThostFtdcLinkManField_Address_get(swigCPtr, this);
	}

	public void setZipCode(String value) {
		CtpJNI.CThostFtdcLinkManField_ZipCode_set(swigCPtr, this, value);
	}

	public String getZipCode() {
		return CtpJNI.CThostFtdcLinkManField_ZipCode_get(swigCPtr, this);
	}

	public void setPriority(int value) {
		CtpJNI.CThostFtdcLinkManField_Priority_set(swigCPtr, this, value);
	}

	public int getPriority() {
		return CtpJNI.CThostFtdcLinkManField_Priority_get(swigCPtr, this);
	}

	public CThostFtdcLinkManField() {
		this(CtpJNI.new_CThostFtdcLinkManField(), true);
	}

}
