/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQryInstrumentMarginRateField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQryInstrumentMarginRateField(long cPtr,
			boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQryInstrumentMarginRateField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQryInstrumentMarginRateField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcQryInstrumentMarginRateField_BrokerID_set(swigCPtr,
				this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcQryInstrumentMarginRateField_BrokerID_get(
				swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcQryInstrumentMarginRateField_InvestorID_set(swigCPtr,
				this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcQryInstrumentMarginRateField_InvestorID_get(
				swigCPtr, this);
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcQryInstrumentMarginRateField_InstrumentID_set(
				swigCPtr, this, value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcQryInstrumentMarginRateField_InstrumentID_get(
				swigCPtr, this);
	}

	public void setHedgeFlag(char value) {
		CtpJNI.CThostFtdcQryInstrumentMarginRateField_HedgeFlag_set(swigCPtr,
				this, value);
	}

	public char getHedgeFlag() {
		return CtpJNI.CThostFtdcQryInstrumentMarginRateField_HedgeFlag_get(
				swigCPtr, this);
	}

	public CThostFtdcQryInstrumentMarginRateField() {
		this(CtpJNI.new_CThostFtdcQryInstrumentMarginRateField(), true);
	}

}
