/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcFrontStatusField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcFrontStatusField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcFrontStatusField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcFrontStatusField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setFrontID(int value) {
		CtpJNI.CThostFtdcFrontStatusField_FrontID_set(swigCPtr, this, value);
	}

	public int getFrontID() {
		return CtpJNI.CThostFtdcFrontStatusField_FrontID_get(swigCPtr, this);
	}

	public void setLastReportDate(String value) {
		CtpJNI.CThostFtdcFrontStatusField_LastReportDate_set(swigCPtr, this,
				value);
	}

	public String getLastReportDate() {
		return CtpJNI.CThostFtdcFrontStatusField_LastReportDate_get(swigCPtr,
				this);
	}

	public void setLastReportTime(String value) {
		CtpJNI.CThostFtdcFrontStatusField_LastReportTime_set(swigCPtr, this,
				value);
	}

	public String getLastReportTime() {
		return CtpJNI.CThostFtdcFrontStatusField_LastReportTime_get(swigCPtr,
				this);
	}

	public void setIsActive(int value) {
		CtpJNI.CThostFtdcFrontStatusField_IsActive_set(swigCPtr, this, value);
	}

	public int getIsActive() {
		return CtpJNI.CThostFtdcFrontStatusField_IsActive_get(swigCPtr, this);
	}

	public CThostFtdcFrontStatusField() {
		this(CtpJNI.new_CThostFtdcFrontStatusField(), true);
	}

}
