/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcCancelAccountField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcCancelAccountField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcCancelAccountField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcCancelAccountField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcCancelAccountField_TradeCode_set(swigCPtr, this, value);
	}

	public String getTradeCode() {
		return CtpJNI
				.CThostFtdcCancelAccountField_TradeCode_get(swigCPtr, this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BankID_set(swigCPtr, this, value);
	}

	public String getBankID() {
		return CtpJNI.CThostFtdcCancelAccountField_BankID_get(swigCPtr, this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BankBranchID_set(swigCPtr, this,
				value);
	}

	public String getBankBranchID() {
		return CtpJNI.CThostFtdcCancelAccountField_BankBranchID_get(swigCPtr,
				this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcCancelAccountField_BrokerID_get(swigCPtr, this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BrokerBranchID_set(swigCPtr, this,
				value);
	}

	public String getBrokerBranchID() {
		return CtpJNI.CThostFtdcCancelAccountField_BrokerBranchID_get(swigCPtr,
				this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcCancelAccountField_TradeDate_set(swigCPtr, this, value);
	}

	public String getTradeDate() {
		return CtpJNI
				.CThostFtdcCancelAccountField_TradeDate_get(swigCPtr, this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcCancelAccountField_TradeTime_set(swigCPtr, this, value);
	}

	public String getTradeTime() {
		return CtpJNI
				.CThostFtdcCancelAccountField_TradeTime_get(swigCPtr, this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BankSerial_set(swigCPtr, this,
				value);
	}

	public String getBankSerial() {
		return CtpJNI.CThostFtdcCancelAccountField_BankSerial_get(swigCPtr,
				this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcCancelAccountField_TradingDay_set(swigCPtr, this,
				value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcCancelAccountField_TradingDay_get(swigCPtr,
				this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcCancelAccountField_PlateSerial_set(swigCPtr, this,
				value);
	}

	public int getPlateSerial() {
		return CtpJNI.CThostFtdcCancelAccountField_PlateSerial_get(swigCPtr,
				this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcCancelAccountField_LastFragment_set(swigCPtr, this,
				value);
	}

	public char getLastFragment() {
		return CtpJNI.CThostFtdcCancelAccountField_LastFragment_get(swigCPtr,
				this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcCancelAccountField_SessionID_set(swigCPtr, this, value);
	}

	public int getSessionID() {
		return CtpJNI
				.CThostFtdcCancelAccountField_SessionID_get(swigCPtr, this);
	}

	public void setCustomerName(String value) {
		CtpJNI.CThostFtdcCancelAccountField_CustomerName_set(swigCPtr, this,
				value);
	}

	public String getCustomerName() {
		return CtpJNI.CThostFtdcCancelAccountField_CustomerName_get(swigCPtr,
				this);
	}

	public void setIdCardType(char value) {
		CtpJNI.CThostFtdcCancelAccountField_IdCardType_set(swigCPtr, this,
				value);
	}

	public char getIdCardType() {
		return CtpJNI.CThostFtdcCancelAccountField_IdCardType_get(swigCPtr,
				this);
	}

	public void setIdentifiedCardNo(String value) {
		CtpJNI.CThostFtdcCancelAccountField_IdentifiedCardNo_set(swigCPtr,
				this, value);
	}

	public String getIdentifiedCardNo() {
		return CtpJNI.CThostFtdcCancelAccountField_IdentifiedCardNo_get(
				swigCPtr, this);
	}

	public void setGender(char value) {
		CtpJNI.CThostFtdcCancelAccountField_Gender_set(swigCPtr, this, value);
	}

	public char getGender() {
		return CtpJNI.CThostFtdcCancelAccountField_Gender_get(swigCPtr, this);
	}

	public void setCountryCode(String value) {
		CtpJNI.CThostFtdcCancelAccountField_CountryCode_set(swigCPtr, this,
				value);
	}

	public String getCountryCode() {
		return CtpJNI.CThostFtdcCancelAccountField_CountryCode_get(swigCPtr,
				this);
	}

	public void setCustType(char value) {
		CtpJNI.CThostFtdcCancelAccountField_CustType_set(swigCPtr, this, value);
	}

	public char getCustType() {
		return CtpJNI.CThostFtdcCancelAccountField_CustType_get(swigCPtr, this);
	}

	public void setAddress(String value) {
		CtpJNI.CThostFtdcCancelAccountField_Address_set(swigCPtr, this, value);
	}

	public String getAddress() {
		return CtpJNI.CThostFtdcCancelAccountField_Address_get(swigCPtr, this);
	}

	public void setZipCode(String value) {
		CtpJNI.CThostFtdcCancelAccountField_ZipCode_set(swigCPtr, this, value);
	}

	public String getZipCode() {
		return CtpJNI.CThostFtdcCancelAccountField_ZipCode_get(swigCPtr, this);
	}

	public void setTelephone(String value) {
		CtpJNI.CThostFtdcCancelAccountField_Telephone_set(swigCPtr, this, value);
	}

	public String getTelephone() {
		return CtpJNI
				.CThostFtdcCancelAccountField_Telephone_get(swigCPtr, this);
	}

	public void setMobilePhone(String value) {
		CtpJNI.CThostFtdcCancelAccountField_MobilePhone_set(swigCPtr, this,
				value);
	}

	public String getMobilePhone() {
		return CtpJNI.CThostFtdcCancelAccountField_MobilePhone_get(swigCPtr,
				this);
	}

	public void setFax(String value) {
		CtpJNI.CThostFtdcCancelAccountField_Fax_set(swigCPtr, this, value);
	}

	public String getFax() {
		return CtpJNI.CThostFtdcCancelAccountField_Fax_get(swigCPtr, this);
	}

	public void setEMail(String value) {
		CtpJNI.CThostFtdcCancelAccountField_EMail_set(swigCPtr, this, value);
	}

	public String getEMail() {
		return CtpJNI.CThostFtdcCancelAccountField_EMail_get(swigCPtr, this);
	}

	public void setMoneyAccountStatus(char value) {
		CtpJNI.CThostFtdcCancelAccountField_MoneyAccountStatus_set(swigCPtr,
				this, value);
	}

	public char getMoneyAccountStatus() {
		return CtpJNI.CThostFtdcCancelAccountField_MoneyAccountStatus_get(
				swigCPtr, this);
	}

	public void setBankAccount(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BankAccount_set(swigCPtr, this,
				value);
	}

	public String getBankAccount() {
		return CtpJNI.CThostFtdcCancelAccountField_BankAccount_get(swigCPtr,
				this);
	}

	public void setBankPassWord(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BankPassWord_set(swigCPtr, this,
				value);
	}

	public String getBankPassWord() {
		return CtpJNI.CThostFtdcCancelAccountField_BankPassWord_get(swigCPtr,
				this);
	}

	public void setAccountID(String value) {
		CtpJNI.CThostFtdcCancelAccountField_AccountID_set(swigCPtr, this, value);
	}

	public String getAccountID() {
		return CtpJNI
				.CThostFtdcCancelAccountField_AccountID_get(swigCPtr, this);
	}

	public void setPassword(String value) {
		CtpJNI.CThostFtdcCancelAccountField_Password_set(swigCPtr, this, value);
	}

	public String getPassword() {
		return CtpJNI.CThostFtdcCancelAccountField_Password_get(swigCPtr, this);
	}

	public void setInstallID(int value) {
		CtpJNI.CThostFtdcCancelAccountField_InstallID_set(swigCPtr, this, value);
	}

	public int getInstallID() {
		return CtpJNI
				.CThostFtdcCancelAccountField_InstallID_get(swigCPtr, this);
	}

	public void setVerifyCertNoFlag(char value) {
		CtpJNI.CThostFtdcCancelAccountField_VerifyCertNoFlag_set(swigCPtr,
				this, value);
	}

	public char getVerifyCertNoFlag() {
		return CtpJNI.CThostFtdcCancelAccountField_VerifyCertNoFlag_get(
				swigCPtr, this);
	}

	public void setCurrencyID(String value) {
		CtpJNI.CThostFtdcCancelAccountField_CurrencyID_set(swigCPtr, this,
				value);
	}

	public String getCurrencyID() {
		return CtpJNI.CThostFtdcCancelAccountField_CurrencyID_get(swigCPtr,
				this);
	}

	public void setCashExchangeCode(char value) {
		CtpJNI.CThostFtdcCancelAccountField_CashExchangeCode_set(swigCPtr,
				this, value);
	}

	public char getCashExchangeCode() {
		return CtpJNI.CThostFtdcCancelAccountField_CashExchangeCode_get(
				swigCPtr, this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcCancelAccountField_Digest_set(swigCPtr, this, value);
	}

	public String getDigest() {
		return CtpJNI.CThostFtdcCancelAccountField_Digest_get(swigCPtr, this);
	}

	public void setBankAccType(char value) {
		CtpJNI.CThostFtdcCancelAccountField_BankAccType_set(swigCPtr, this,
				value);
	}

	public char getBankAccType() {
		return CtpJNI.CThostFtdcCancelAccountField_BankAccType_get(swigCPtr,
				this);
	}

	public void setDeviceID(String value) {
		CtpJNI.CThostFtdcCancelAccountField_DeviceID_set(swigCPtr, this, value);
	}

	public String getDeviceID() {
		return CtpJNI.CThostFtdcCancelAccountField_DeviceID_get(swigCPtr, this);
	}

	public void setBankSecuAccType(char value) {
		CtpJNI.CThostFtdcCancelAccountField_BankSecuAccType_set(swigCPtr, this,
				value);
	}

	public char getBankSecuAccType() {
		return CtpJNI.CThostFtdcCancelAccountField_BankSecuAccType_get(
				swigCPtr, this);
	}

	public void setBrokerIDByBank(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BrokerIDByBank_set(swigCPtr, this,
				value);
	}

	public String getBrokerIDByBank() {
		return CtpJNI.CThostFtdcCancelAccountField_BrokerIDByBank_get(swigCPtr,
				this);
	}

	public void setBankSecuAcc(String value) {
		CtpJNI.CThostFtdcCancelAccountField_BankSecuAcc_set(swigCPtr, this,
				value);
	}

	public String getBankSecuAcc() {
		return CtpJNI.CThostFtdcCancelAccountField_BankSecuAcc_get(swigCPtr,
				this);
	}

	public void setBankPwdFlag(char value) {
		CtpJNI.CThostFtdcCancelAccountField_BankPwdFlag_set(swigCPtr, this,
				value);
	}

	public char getBankPwdFlag() {
		return CtpJNI.CThostFtdcCancelAccountField_BankPwdFlag_get(swigCPtr,
				this);
	}

	public void setSecuPwdFlag(char value) {
		CtpJNI.CThostFtdcCancelAccountField_SecuPwdFlag_set(swigCPtr, this,
				value);
	}

	public char getSecuPwdFlag() {
		return CtpJNI.CThostFtdcCancelAccountField_SecuPwdFlag_get(swigCPtr,
				this);
	}

	public void setOperNo(String value) {
		CtpJNI.CThostFtdcCancelAccountField_OperNo_set(swigCPtr, this, value);
	}

	public String getOperNo() {
		return CtpJNI.CThostFtdcCancelAccountField_OperNo_get(swigCPtr, this);
	}

	public void setTID(int value) {
		CtpJNI.CThostFtdcCancelAccountField_TID_set(swigCPtr, this, value);
	}

	public int getTID() {
		return CtpJNI.CThostFtdcCancelAccountField_TID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcCancelAccountField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcCancelAccountField_UserID_get(swigCPtr, this);
	}

	public void setErrorID(int value) {
		CtpJNI.CThostFtdcCancelAccountField_ErrorID_set(swigCPtr, this, value);
	}

	public int getErrorID() {
		return CtpJNI.CThostFtdcCancelAccountField_ErrorID_get(swigCPtr, this);
	}

	public void setErrorMsg(String value) {
		CtpJNI.CThostFtdcCancelAccountField_ErrorMsg_set(swigCPtr, this, value);
	}

	public String getErrorMsg() {
		return CtpJNI.CThostFtdcCancelAccountField_ErrorMsg_get(swigCPtr, this);
	}

	public CThostFtdcCancelAccountField() {
		this(CtpJNI.new_CThostFtdcCancelAccountField(), true);
	}

}
