/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcTradingNoticeInfoField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcTradingNoticeInfoField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcTradingNoticeInfoField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcTradingNoticeInfoField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcTradingNoticeInfoField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcTradingNoticeInfoField_BrokerID_get(swigCPtr,
				this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcTradingNoticeInfoField_InvestorID_set(swigCPtr, this,
				value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcTradingNoticeInfoField_InvestorID_get(swigCPtr,
				this);
	}

	public void setSendTime(String value) {
		CtpJNI.CThostFtdcTradingNoticeInfoField_SendTime_set(swigCPtr, this,
				value);
	}

	public String getSendTime() {
		return CtpJNI.CThostFtdcTradingNoticeInfoField_SendTime_get(swigCPtr,
				this);
	}

	public void setFieldContent(String value) {
		CtpJNI.CThostFtdcTradingNoticeInfoField_FieldContent_set(swigCPtr,
				this, value);
	}

	public String getFieldContent() {
		return CtpJNI.CThostFtdcTradingNoticeInfoField_FieldContent_get(
				swigCPtr, this);
	}

	public void setSequenceSeries(short value) {
		CtpJNI.CThostFtdcTradingNoticeInfoField_SequenceSeries_set(swigCPtr,
				this, value);
	}

	public short getSequenceSeries() {
		return CtpJNI.CThostFtdcTradingNoticeInfoField_SequenceSeries_get(
				swigCPtr, this);
	}

	public void setSequenceNo(int value) {
		CtpJNI.CThostFtdcTradingNoticeInfoField_SequenceNo_set(swigCPtr, this,
				value);
	}

	public int getSequenceNo() {
		return CtpJNI.CThostFtdcTradingNoticeInfoField_SequenceNo_get(swigCPtr,
				this);
	}

	public CThostFtdcTradingNoticeInfoField() {
		this(CtpJNI.new_CThostFtdcTradingNoticeInfoField(), true);
	}

}
