/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcUserRightField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcUserRightField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcUserRightField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcUserRightField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcUserRightField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcUserRightField_BrokerID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcUserRightField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcUserRightField_UserID_get(swigCPtr, this);
	}

	public void setUserRightType(char value) {
		CtpJNI.CThostFtdcUserRightField_UserRightType_set(swigCPtr, this, value);
	}

	public char getUserRightType() {
		return CtpJNI
				.CThostFtdcUserRightField_UserRightType_get(swigCPtr, this);
	}

	public void setIsForbidden(int value) {
		CtpJNI.CThostFtdcUserRightField_IsForbidden_set(swigCPtr, this, value);
	}

	public int getIsForbidden() {
		return CtpJNI.CThostFtdcUserRightField_IsForbidden_get(swigCPtr, this);
	}

	public CThostFtdcUserRightField() {
		this(CtpJNI.new_CThostFtdcUserRightField(), true);
	}

}
