/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcTransferQryBankRspField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcTransferQryBankRspField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcTransferQryBankRspField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcTransferQryBankRspField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setRetCode(String value) {
		CtpJNI.CThostFtdcTransferQryBankRspField_RetCode_set(swigCPtr, this,
				value);
	}

	public String getRetCode() {
		return CtpJNI.CThostFtdcTransferQryBankRspField_RetCode_get(swigCPtr,
				this);
	}

	public void setRetInfo(String value) {
		CtpJNI.CThostFtdcTransferQryBankRspField_RetInfo_set(swigCPtr, this,
				value);
	}

	public String getRetInfo() {
		return CtpJNI.CThostFtdcTransferQryBankRspField_RetInfo_get(swigCPtr,
				this);
	}

	public void setFutureAccount(String value) {
		CtpJNI.CThostFtdcTransferQryBankRspField_FutureAccount_set(swigCPtr,
				this, value);
	}

	public String getFutureAccount() {
		return CtpJNI.CThostFtdcTransferQryBankRspField_FutureAccount_get(
				swigCPtr, this);
	}

	public void setTradeAmt(double value) {
		CtpJNI.CThostFtdcTransferQryBankRspField_TradeAmt_set(swigCPtr, this,
				value);
	}

	public double getTradeAmt() {
		return CtpJNI.CThostFtdcTransferQryBankRspField_TradeAmt_get(swigCPtr,
				this);
	}

	public void setUseAmt(double value) {
		CtpJNI.CThostFtdcTransferQryBankRspField_UseAmt_set(swigCPtr, this,
				value);
	}

	public double getUseAmt() {
		return CtpJNI.CThostFtdcTransferQryBankRspField_UseAmt_get(swigCPtr,
				this);
	}

	public void setFetchAmt(double value) {
		CtpJNI.CThostFtdcTransferQryBankRspField_FetchAmt_set(swigCPtr, this,
				value);
	}

	public double getFetchAmt() {
		return CtpJNI.CThostFtdcTransferQryBankRspField_FetchAmt_get(swigCPtr,
				this);
	}

	public void setCurrencyCode(String value) {
		CtpJNI.CThostFtdcTransferQryBankRspField_CurrencyCode_set(swigCPtr,
				this, value);
	}

	public String getCurrencyCode() {
		return CtpJNI.CThostFtdcTransferQryBankRspField_CurrencyCode_get(
				swigCPtr, this);
	}

	public CThostFtdcTransferQryBankRspField() {
		this(CtpJNI.new_CThostFtdcTransferQryBankRspField(), true);
	}

}
