/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcInvestorField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcInvestorField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcInvestorField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcInvestorField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcInvestorField_InvestorID_set(swigCPtr, this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcInvestorField_InvestorID_get(swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcInvestorField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcInvestorField_BrokerID_get(swigCPtr, this);
	}

	public void setInvestorGroupID(String value) {
		CtpJNI.CThostFtdcInvestorField_InvestorGroupID_set(swigCPtr, this,
				value);
	}

	public String getInvestorGroupID() {
		return CtpJNI.CThostFtdcInvestorField_InvestorGroupID_get(swigCPtr,
				this);
	}

	public void setInvestorName(String value) {
		CtpJNI.CThostFtdcInvestorField_InvestorName_set(swigCPtr, this, value);
	}

	public String getInvestorName() {
		return CtpJNI.CThostFtdcInvestorField_InvestorName_get(swigCPtr, this);
	}

	public void setIdentifiedCardType(char value) {
		CtpJNI.CThostFtdcInvestorField_IdentifiedCardType_set(swigCPtr, this,
				value);
	}

	public char getIdentifiedCardType() {
		return CtpJNI.CThostFtdcInvestorField_IdentifiedCardType_get(swigCPtr,
				this);
	}

	public void setIdentifiedCardNo(String value) {
		CtpJNI.CThostFtdcInvestorField_IdentifiedCardNo_set(swigCPtr, this,
				value);
	}

	public String getIdentifiedCardNo() {
		return CtpJNI.CThostFtdcInvestorField_IdentifiedCardNo_get(swigCPtr,
				this);
	}

	public void setIsActive(int value) {
		CtpJNI.CThostFtdcInvestorField_IsActive_set(swigCPtr, this, value);
	}

	public int getIsActive() {
		return CtpJNI.CThostFtdcInvestorField_IsActive_get(swigCPtr, this);
	}

	public void setTelephone(String value) {
		CtpJNI.CThostFtdcInvestorField_Telephone_set(swigCPtr, this, value);
	}

	public String getTelephone() {
		return CtpJNI.CThostFtdcInvestorField_Telephone_get(swigCPtr, this);
	}

	public void setAddress(String value) {
		CtpJNI.CThostFtdcInvestorField_Address_set(swigCPtr, this, value);
	}

	public String getAddress() {
		return CtpJNI.CThostFtdcInvestorField_Address_get(swigCPtr, this);
	}

	public void setOpenDate(String value) {
		CtpJNI.CThostFtdcInvestorField_OpenDate_set(swigCPtr, this, value);
	}

	public String getOpenDate() {
		return CtpJNI.CThostFtdcInvestorField_OpenDate_get(swigCPtr, this);
	}

	public void setMobile(String value) {
		CtpJNI.CThostFtdcInvestorField_Mobile_set(swigCPtr, this, value);
	}

	public String getMobile() {
		return CtpJNI.CThostFtdcInvestorField_Mobile_get(swigCPtr, this);
	}

	public void setCommModelID(String value) {
		CtpJNI.CThostFtdcInvestorField_CommModelID_set(swigCPtr, this, value);
	}

	public String getCommModelID() {
		return CtpJNI.CThostFtdcInvestorField_CommModelID_get(swigCPtr, this);
	}

	public void setMarginModelID(String value) {
		CtpJNI.CThostFtdcInvestorField_MarginModelID_set(swigCPtr, this, value);
	}

	public String getMarginModelID() {
		return CtpJNI.CThostFtdcInvestorField_MarginModelID_get(swigCPtr, this);
	}

	public CThostFtdcInvestorField() {
		this(CtpJNI.new_CThostFtdcInvestorField(), true);
	}

}
