/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcRspUserLoginField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcRspUserLoginField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcRspUserLoginField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcRspUserLoginField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_TradingDay_set(swigCPtr, this, value);
	}

	public String getTradingDay() {
		return CtpJNI
				.CThostFtdcRspUserLoginField_TradingDay_get(swigCPtr, this);
	}

	public void setLoginTime(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_LoginTime_set(swigCPtr, this, value);
	}

	public String getLoginTime() {
		return CtpJNI.CThostFtdcRspUserLoginField_LoginTime_get(swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcRspUserLoginField_BrokerID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcRspUserLoginField_UserID_get(swigCPtr, this);
	}

	public void setSystemName(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_SystemName_set(swigCPtr, this, value);
	}

	public String getSystemName() {
		return CtpJNI
				.CThostFtdcRspUserLoginField_SystemName_get(swigCPtr, this);
	}

	public void setFrontID(int value) {
		CtpJNI.CThostFtdcRspUserLoginField_FrontID_set(swigCPtr, this, value);
	}

	public int getFrontID() {
		return CtpJNI.CThostFtdcRspUserLoginField_FrontID_get(swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcRspUserLoginField_SessionID_set(swigCPtr, this, value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcRspUserLoginField_SessionID_get(swigCPtr, this);
	}

	public void setMaxOrderRef(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_MaxOrderRef_set(swigCPtr, this,
				value);
	}

	public String getMaxOrderRef() {
		return CtpJNI.CThostFtdcRspUserLoginField_MaxOrderRef_get(swigCPtr,
				this);
	}

	public void setSHFETime(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_SHFETime_set(swigCPtr, this, value);
	}

	public String getSHFETime() {
		return CtpJNI.CThostFtdcRspUserLoginField_SHFETime_get(swigCPtr, this);
	}

	public void setDCETime(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_DCETime_set(swigCPtr, this, value);
	}

	public String getDCETime() {
		return CtpJNI.CThostFtdcRspUserLoginField_DCETime_get(swigCPtr, this);
	}

	public void setCZCETime(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_CZCETime_set(swigCPtr, this, value);
	}

	public String getCZCETime() {
		return CtpJNI.CThostFtdcRspUserLoginField_CZCETime_get(swigCPtr, this);
	}

	public void setFFEXTime(String value) {
		CtpJNI.CThostFtdcRspUserLoginField_FFEXTime_set(swigCPtr, this, value);
	}

	public String getFFEXTime() {
		return CtpJNI.CThostFtdcRspUserLoginField_FFEXTime_get(swigCPtr, this);
	}

	public CThostFtdcRspUserLoginField() {
		this(CtpJNI.new_CThostFtdcRspUserLoginField(), true);
	}

}
