/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcMarketDataAveragePriceField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcMarketDataAveragePriceField(long cPtr,
			boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcMarketDataAveragePriceField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcMarketDataAveragePriceField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setAveragePrice(double value) {
		CtpJNI.CThostFtdcMarketDataAveragePriceField_AveragePrice_set(swigCPtr,
				this, value);
	}

	public double getAveragePrice() {
		return CtpJNI.CThostFtdcMarketDataAveragePriceField_AveragePrice_get(
				swigCPtr, this);
	}

	public CThostFtdcMarketDataAveragePriceField() {
		this(CtpJNI.new_CThostFtdcMarketDataAveragePriceField(), true);
	}

}
