/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcUserIPField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcUserIPField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcUserIPField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcUserIPField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcUserIPField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcUserIPField_BrokerID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcUserIPField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcUserIPField_UserID_get(swigCPtr, this);
	}

	public void setIPAddress(String value) {
		CtpJNI.CThostFtdcUserIPField_IPAddress_set(swigCPtr, this, value);
	}

	public String getIPAddress() {
		return CtpJNI.CThostFtdcUserIPField_IPAddress_get(swigCPtr, this);
	}

	public void setIPMask(String value) {
		CtpJNI.CThostFtdcUserIPField_IPMask_set(swigCPtr, this, value);
	}

	public String getIPMask() {
		return CtpJNI.CThostFtdcUserIPField_IPMask_get(swigCPtr, this);
	}

	public void setMacAddress(String value) {
		CtpJNI.CThostFtdcUserIPField_MacAddress_set(swigCPtr, this, value);
	}

	public String getMacAddress() {
		return CtpJNI.CThostFtdcUserIPField_MacAddress_get(swigCPtr, this);
	}

	public CThostFtdcUserIPField() {
		this(CtpJNI.new_CThostFtdcUserIPField(), true);
	}

}
