/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcEWarrantOffsetField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcEWarrantOffsetField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcEWarrantOffsetField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcEWarrantOffsetField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcEWarrantOffsetField_TradingDay_set(swigCPtr, this,
				value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcEWarrantOffsetField_TradingDay_get(swigCPtr,
				this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcEWarrantOffsetField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI
				.CThostFtdcEWarrantOffsetField_BrokerID_get(swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcEWarrantOffsetField_InvestorID_set(swigCPtr, this,
				value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcEWarrantOffsetField_InvestorID_get(swigCPtr,
				this);
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcEWarrantOffsetField_ExchangeID_set(swigCPtr, this,
				value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcEWarrantOffsetField_ExchangeID_get(swigCPtr,
				this);
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcEWarrantOffsetField_InstrumentID_set(swigCPtr, this,
				value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcEWarrantOffsetField_InstrumentID_get(swigCPtr,
				this);
	}

	public void setDirection(char value) {
		CtpJNI.CThostFtdcEWarrantOffsetField_Direction_set(swigCPtr, this,
				value);
	}

	public char getDirection() {
		return CtpJNI.CThostFtdcEWarrantOffsetField_Direction_get(swigCPtr,
				this);
	}

	public void setHedgeFlag(char value) {
		CtpJNI.CThostFtdcEWarrantOffsetField_HedgeFlag_set(swigCPtr, this,
				value);
	}

	public char getHedgeFlag() {
		return CtpJNI.CThostFtdcEWarrantOffsetField_HedgeFlag_get(swigCPtr,
				this);
	}

	public void setVolume(int value) {
		CtpJNI.CThostFtdcEWarrantOffsetField_Volume_set(swigCPtr, this, value);
	}

	public int getVolume() {
		return CtpJNI.CThostFtdcEWarrantOffsetField_Volume_get(swigCPtr, this);
	}

	public CThostFtdcEWarrantOffsetField() {
		this(CtpJNI.new_CThostFtdcEWarrantOffsetField(), true);
	}

}
