/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcExchangeField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcExchangeField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcExchangeField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcExchangeField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcExchangeField_ExchangeID_set(swigCPtr, this, value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcExchangeField_ExchangeID_get(swigCPtr, this);
	}

	public void setExchangeName(String value) {
		CtpJNI.CThostFtdcExchangeField_ExchangeName_set(swigCPtr, this, value);
	}

	public String getExchangeName() {
		return CtpJNI.CThostFtdcExchangeField_ExchangeName_get(swigCPtr, this);
	}

	public void setExchangeProperty(char value) {
		CtpJNI.CThostFtdcExchangeField_ExchangeProperty_set(swigCPtr, this,
				value);
	}

	public char getExchangeProperty() {
		return CtpJNI.CThostFtdcExchangeField_ExchangeProperty_get(swigCPtr,
				this);
	}

	public CThostFtdcExchangeField() {
		this(CtpJNI.new_CThostFtdcExchangeField(), true);
	}

}
