/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcInvestorPositionField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcInvestorPositionField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcInvestorPositionField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcInvestorPositionField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcInvestorPositionField_InstrumentID_set(swigCPtr, this,
				value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcInvestorPositionField_InstrumentID_get(
				swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcInvestorPositionField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcInvestorPositionField_BrokerID_get(swigCPtr,
				this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcInvestorPositionField_InvestorID_set(swigCPtr, this,
				value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcInvestorPositionField_InvestorID_get(swigCPtr,
				this);
	}

	public void setPosiDirection(char value) {
		CtpJNI.CThostFtdcInvestorPositionField_PosiDirection_set(swigCPtr,
				this, value);
	}

	public char getPosiDirection() {
		return CtpJNI.CThostFtdcInvestorPositionField_PosiDirection_get(
				swigCPtr, this);
	}

	public void setHedgeFlag(char value) {
		CtpJNI.CThostFtdcInvestorPositionField_HedgeFlag_set(swigCPtr, this,
				value);
	}

	public char getHedgeFlag() {
		return CtpJNI.CThostFtdcInvestorPositionField_HedgeFlag_get(swigCPtr,
				this);
	}

	public void setPositionDate(char value) {
		CtpJNI.CThostFtdcInvestorPositionField_PositionDate_set(swigCPtr, this,
				value);
	}

	public char getPositionDate() {
		return CtpJNI.CThostFtdcInvestorPositionField_PositionDate_get(
				swigCPtr, this);
	}

	public void setYdPosition(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_YdPosition_set(swigCPtr, this,
				value);
	}

	public int getYdPosition() {
		return CtpJNI.CThostFtdcInvestorPositionField_YdPosition_get(swigCPtr,
				this);
	}

	public void setPosition(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_Position_set(swigCPtr, this,
				value);
	}

	public int getPosition() {
		return CtpJNI.CThostFtdcInvestorPositionField_Position_get(swigCPtr,
				this);
	}

	public void setLongFrozen(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_LongFrozen_set(swigCPtr, this,
				value);
	}

	public int getLongFrozen() {
		return CtpJNI.CThostFtdcInvestorPositionField_LongFrozen_get(swigCPtr,
				this);
	}

	public void setShortFrozen(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_ShortFrozen_set(swigCPtr, this,
				value);
	}

	public int getShortFrozen() {
		return CtpJNI.CThostFtdcInvestorPositionField_ShortFrozen_get(swigCPtr,
				this);
	}

	public void setLongFrozenAmount(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_LongFrozenAmount_set(swigCPtr,
				this, value);
	}

	public double getLongFrozenAmount() {
		return CtpJNI.CThostFtdcInvestorPositionField_LongFrozenAmount_get(
				swigCPtr, this);
	}

	public void setShortFrozenAmount(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_ShortFrozenAmount_set(swigCPtr,
				this, value);
	}

	public double getShortFrozenAmount() {
		return CtpJNI.CThostFtdcInvestorPositionField_ShortFrozenAmount_get(
				swigCPtr, this);
	}

	public void setOpenVolume(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_OpenVolume_set(swigCPtr, this,
				value);
	}

	public int getOpenVolume() {
		return CtpJNI.CThostFtdcInvestorPositionField_OpenVolume_get(swigCPtr,
				this);
	}

	public void setCloseVolume(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_CloseVolume_set(swigCPtr, this,
				value);
	}

	public int getCloseVolume() {
		return CtpJNI.CThostFtdcInvestorPositionField_CloseVolume_get(swigCPtr,
				this);
	}

	public void setOpenAmount(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_OpenAmount_set(swigCPtr, this,
				value);
	}

	public double getOpenAmount() {
		return CtpJNI.CThostFtdcInvestorPositionField_OpenAmount_get(swigCPtr,
				this);
	}

	public void setCloseAmount(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_CloseAmount_set(swigCPtr, this,
				value);
	}

	public double getCloseAmount() {
		return CtpJNI.CThostFtdcInvestorPositionField_CloseAmount_get(swigCPtr,
				this);
	}

	public void setPositionCost(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_PositionCost_set(swigCPtr, this,
				value);
	}

	public double getPositionCost() {
		return CtpJNI.CThostFtdcInvestorPositionField_PositionCost_get(
				swigCPtr, this);
	}

	public void setPreMargin(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_PreMargin_set(swigCPtr, this,
				value);
	}

	public double getPreMargin() {
		return CtpJNI.CThostFtdcInvestorPositionField_PreMargin_get(swigCPtr,
				this);
	}

	public void setUseMargin(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_UseMargin_set(swigCPtr, this,
				value);
	}

	public double getUseMargin() {
		return CtpJNI.CThostFtdcInvestorPositionField_UseMargin_get(swigCPtr,
				this);
	}

	public void setFrozenMargin(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_FrozenMargin_set(swigCPtr, this,
				value);
	}

	public double getFrozenMargin() {
		return CtpJNI.CThostFtdcInvestorPositionField_FrozenMargin_get(
				swigCPtr, this);
	}

	public void setFrozenCash(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_FrozenCash_set(swigCPtr, this,
				value);
	}

	public double getFrozenCash() {
		return CtpJNI.CThostFtdcInvestorPositionField_FrozenCash_get(swigCPtr,
				this);
	}

	public void setFrozenCommission(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_FrozenCommission_set(swigCPtr,
				this, value);
	}

	public double getFrozenCommission() {
		return CtpJNI.CThostFtdcInvestorPositionField_FrozenCommission_get(
				swigCPtr, this);
	}

	public void setCashIn(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_CashIn_set(swigCPtr, this, value);
	}

	public double getCashIn() {
		return CtpJNI
				.CThostFtdcInvestorPositionField_CashIn_get(swigCPtr, this);
	}

	public void setCommission(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_Commission_set(swigCPtr, this,
				value);
	}

	public double getCommission() {
		return CtpJNI.CThostFtdcInvestorPositionField_Commission_get(swigCPtr,
				this);
	}

	public void setCloseProfit(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_CloseProfit_set(swigCPtr, this,
				value);
	}

	public double getCloseProfit() {
		return CtpJNI.CThostFtdcInvestorPositionField_CloseProfit_get(swigCPtr,
				this);
	}

	public void setPositionProfit(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_PositionProfit_set(swigCPtr,
				this, value);
	}

	public double getPositionProfit() {
		return CtpJNI.CThostFtdcInvestorPositionField_PositionProfit_get(
				swigCPtr, this);
	}

	public void setPreSettlementPrice(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_PreSettlementPrice_set(swigCPtr,
				this, value);
	}

	public double getPreSettlementPrice() {
		return CtpJNI.CThostFtdcInvestorPositionField_PreSettlementPrice_get(
				swigCPtr, this);
	}

	public void setSettlementPrice(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_SettlementPrice_set(swigCPtr,
				this, value);
	}

	public double getSettlementPrice() {
		return CtpJNI.CThostFtdcInvestorPositionField_SettlementPrice_get(
				swigCPtr, this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcInvestorPositionField_TradingDay_set(swigCPtr, this,
				value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcInvestorPositionField_TradingDay_get(swigCPtr,
				this);
	}

	public void setSettlementID(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_SettlementID_set(swigCPtr, this,
				value);
	}

	public int getSettlementID() {
		return CtpJNI.CThostFtdcInvestorPositionField_SettlementID_get(
				swigCPtr, this);
	}

	public void setOpenCost(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_OpenCost_set(swigCPtr, this,
				value);
	}

	public double getOpenCost() {
		return CtpJNI.CThostFtdcInvestorPositionField_OpenCost_get(swigCPtr,
				this);
	}

	public void setExchangeMargin(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_ExchangeMargin_set(swigCPtr,
				this, value);
	}

	public double getExchangeMargin() {
		return CtpJNI.CThostFtdcInvestorPositionField_ExchangeMargin_get(
				swigCPtr, this);
	}

	public void setCombPosition(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_CombPosition_set(swigCPtr, this,
				value);
	}

	public int getCombPosition() {
		return CtpJNI.CThostFtdcInvestorPositionField_CombPosition_get(
				swigCPtr, this);
	}

	public void setCombLongFrozen(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_CombLongFrozen_set(swigCPtr,
				this, value);
	}

	public int getCombLongFrozen() {
		return CtpJNI.CThostFtdcInvestorPositionField_CombLongFrozen_get(
				swigCPtr, this);
	}

	public void setCombShortFrozen(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_CombShortFrozen_set(swigCPtr,
				this, value);
	}

	public int getCombShortFrozen() {
		return CtpJNI.CThostFtdcInvestorPositionField_CombShortFrozen_get(
				swigCPtr, this);
	}

	public void setCloseProfitByDate(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_CloseProfitByDate_set(swigCPtr,
				this, value);
	}

	public double getCloseProfitByDate() {
		return CtpJNI.CThostFtdcInvestorPositionField_CloseProfitByDate_get(
				swigCPtr, this);
	}

	public void setCloseProfitByTrade(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_CloseProfitByTrade_set(swigCPtr,
				this, value);
	}

	public double getCloseProfitByTrade() {
		return CtpJNI.CThostFtdcInvestorPositionField_CloseProfitByTrade_get(
				swigCPtr, this);
	}

	public void setTodayPosition(int value) {
		CtpJNI.CThostFtdcInvestorPositionField_TodayPosition_set(swigCPtr,
				this, value);
	}

	public int getTodayPosition() {
		return CtpJNI.CThostFtdcInvestorPositionField_TodayPosition_get(
				swigCPtr, this);
	}

	public void setMarginRateByMoney(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_MarginRateByMoney_set(swigCPtr,
				this, value);
	}

	public double getMarginRateByMoney() {
		return CtpJNI.CThostFtdcInvestorPositionField_MarginRateByMoney_get(
				swigCPtr, this);
	}

	public void setMarginRateByVolume(double value) {
		CtpJNI.CThostFtdcInvestorPositionField_MarginRateByVolume_set(swigCPtr,
				this, value);
	}

	public double getMarginRateByVolume() {
		return CtpJNI.CThostFtdcInvestorPositionField_MarginRateByVolume_get(
				swigCPtr, this);
	}

	public CThostFtdcInvestorPositionField() {
		this(CtpJNI.new_CThostFtdcInvestorPositionField(), true);
	}

}
