/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQrySyncDepositField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQrySyncDepositField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQrySyncDepositField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQrySyncDepositField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcQrySyncDepositField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI
				.CThostFtdcQrySyncDepositField_BrokerID_get(swigCPtr, this);
	}

	public void setDepositSeqNo(String value) {
		CtpJNI.CThostFtdcQrySyncDepositField_DepositSeqNo_set(swigCPtr, this,
				value);
	}

	public String getDepositSeqNo() {
		return CtpJNI.CThostFtdcQrySyncDepositField_DepositSeqNo_get(swigCPtr,
				this);
	}

	public CThostFtdcQrySyncDepositField() {
		this(CtpJNI.new_CThostFtdcQrySyncDepositField(), true);
	}

}
