/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcExchangeMarginRateField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcExchangeMarginRateField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcExchangeMarginRateField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcExchangeMarginRateField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcExchangeMarginRateField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcExchangeMarginRateField_BrokerID_get(swigCPtr,
				this);
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcExchangeMarginRateField_InstrumentID_set(swigCPtr,
				this, value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcExchangeMarginRateField_InstrumentID_get(
				swigCPtr, this);
	}

	public void setHedgeFlag(char value) {
		CtpJNI.CThostFtdcExchangeMarginRateField_HedgeFlag_set(swigCPtr, this,
				value);
	}

	public char getHedgeFlag() {
		return CtpJNI.CThostFtdcExchangeMarginRateField_HedgeFlag_get(swigCPtr,
				this);
	}

	public void setLongMarginRatioByMoney(double value) {
		CtpJNI.CThostFtdcExchangeMarginRateField_LongMarginRatioByMoney_set(
				swigCPtr, this, value);
	}

	public double getLongMarginRatioByMoney() {
		return CtpJNI
				.CThostFtdcExchangeMarginRateField_LongMarginRatioByMoney_get(
						swigCPtr, this);
	}

	public void setLongMarginRatioByVolume(double value) {
		CtpJNI.CThostFtdcExchangeMarginRateField_LongMarginRatioByVolume_set(
				swigCPtr, this, value);
	}

	public double getLongMarginRatioByVolume() {
		return CtpJNI
				.CThostFtdcExchangeMarginRateField_LongMarginRatioByVolume_get(
						swigCPtr, this);
	}

	public void setShortMarginRatioByMoney(double value) {
		CtpJNI.CThostFtdcExchangeMarginRateField_ShortMarginRatioByMoney_set(
				swigCPtr, this, value);
	}

	public double getShortMarginRatioByMoney() {
		return CtpJNI
				.CThostFtdcExchangeMarginRateField_ShortMarginRatioByMoney_get(
						swigCPtr, this);
	}

	public void setShortMarginRatioByVolume(double value) {
		CtpJNI.CThostFtdcExchangeMarginRateField_ShortMarginRatioByVolume_set(
				swigCPtr, this, value);
	}

	public double getShortMarginRatioByVolume() {
		return CtpJNI
				.CThostFtdcExchangeMarginRateField_ShortMarginRatioByVolume_get(
						swigCPtr, this);
	}

	public CThostFtdcExchangeMarginRateField() {
		this(CtpJNI.new_CThostFtdcExchangeMarginRateField(), true);
	}

}
