/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQryUserSessionField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQryUserSessionField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQryUserSessionField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQryUserSessionField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setFrontID(int value) {
		CtpJNI.CThostFtdcQryUserSessionField_FrontID_set(swigCPtr, this, value);
	}

	public int getFrontID() {
		return CtpJNI.CThostFtdcQryUserSessionField_FrontID_get(swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcQryUserSessionField_SessionID_set(swigCPtr, this,
				value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcQryUserSessionField_SessionID_get(swigCPtr,
				this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcQryUserSessionField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI
				.CThostFtdcQryUserSessionField_BrokerID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcQryUserSessionField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcQryUserSessionField_UserID_get(swigCPtr, this);
	}

	public CThostFtdcQryUserSessionField() {
		this(CtpJNI.new_CThostFtdcQryUserSessionField(), true);
	}

}
