/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcReqDayEndFileReadyField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcReqDayEndFileReadyField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcReqDayEndFileReadyField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcReqDayEndFileReadyField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_TradeCode_set(swigCPtr, this,
				value);
	}

	public String getTradeCode() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_TradeCode_get(swigCPtr,
				this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_BankID_set(swigCPtr, this,
				value);
	}

	public String getBankID() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_BankID_get(swigCPtr,
				this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_BankBranchID_set(swigCPtr,
				this, value);
	}

	public String getBankBranchID() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_BankBranchID_get(
				swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_BrokerID_get(swigCPtr,
				this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_BrokerBranchID_set(swigCPtr,
				this, value);
	}

	public String getBrokerBranchID() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_BrokerBranchID_get(
				swigCPtr, this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_TradeDate_set(swigCPtr, this,
				value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_TradeDate_get(swigCPtr,
				this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_TradeTime_set(swigCPtr, this,
				value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_TradeTime_get(swigCPtr,
				this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_BankSerial_set(swigCPtr, this,
				value);
	}

	public String getBankSerial() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_BankSerial_get(
				swigCPtr, this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_TradingDay_set(swigCPtr, this,
				value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_TradingDay_get(
				swigCPtr, this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_PlateSerial_set(swigCPtr,
				this, value);
	}

	public int getPlateSerial() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_PlateSerial_get(
				swigCPtr, this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_LastFragment_set(swigCPtr,
				this, value);
	}

	public char getLastFragment() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_LastFragment_get(
				swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_SessionID_set(swigCPtr, this,
				value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_SessionID_get(swigCPtr,
				this);
	}

	public void setFileBusinessCode(char value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_FileBusinessCode_set(swigCPtr,
				this, value);
	}

	public char getFileBusinessCode() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_FileBusinessCode_get(
				swigCPtr, this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcReqDayEndFileReadyField_Digest_set(swigCPtr, this,
				value);
	}

	public String getDigest() {
		return CtpJNI.CThostFtdcReqDayEndFileReadyField_Digest_get(swigCPtr,
				this);
	}

	public CThostFtdcReqDayEndFileReadyField() {
		this(CtpJNI.new_CThostFtdcReqDayEndFileReadyField(), true);
	}

}
