/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQryParkedOrderField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQryParkedOrderField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQryParkedOrderField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQryParkedOrderField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcQryParkedOrderField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI
				.CThostFtdcQryParkedOrderField_BrokerID_get(swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcQryParkedOrderField_InvestorID_set(swigCPtr, this,
				value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcQryParkedOrderField_InvestorID_get(swigCPtr,
				this);
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcQryParkedOrderField_InstrumentID_set(swigCPtr, this,
				value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcQryParkedOrderField_InstrumentID_get(swigCPtr,
				this);
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcQryParkedOrderField_ExchangeID_set(swigCPtr, this,
				value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcQryParkedOrderField_ExchangeID_get(swigCPtr,
				this);
	}

	public CThostFtdcQryParkedOrderField() {
		this(CtpJNI.new_CThostFtdcQryParkedOrderField(), true);
	}

}
