/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package com.ctp.field;

import com.ctp.swig.ctpJNI;

public class CThostFtdcQryProductExchRateField
{
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected CThostFtdcQryProductExchRateField(long cPtr, boolean cMemoryOwn)
	{
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	public static long getCPtr(CThostFtdcQryProductExchRateField obj)
	{
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize()
	{
		delete();
	}

	public synchronized void delete()
	{
		if (swigCPtr != 0)
		{
			if (swigCMemOwn)
			{
				swigCMemOwn = false;
				ctpJNI.delete_CThostFtdcQryProductExchRateField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setProductID(String value)
	{
		ctpJNI.CThostFtdcQryProductExchRateField_ProductID_set(swigCPtr, this, value);
	}

	public String getProductID()
	{
		return ctpJNI.CThostFtdcQryProductExchRateField_ProductID_get(swigCPtr, this);
	}

	public CThostFtdcQryProductExchRateField()
	{
		this(ctpJNI.new_CThostFtdcQryProductExchRateField(), true);
	}
}
