/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcRspFutureSignOutField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcRspFutureSignOutField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcRspFutureSignOutField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcRspFutureSignOutField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_TradeCode_set(swigCPtr, this,
				value);
	}

	public String getTradeCode() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_TradeCode_get(swigCPtr,
				this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_BankID_set(swigCPtr, this, value);
	}

	public String getBankID() {
		return CtpJNI
				.CThostFtdcRspFutureSignOutField_BankID_get(swigCPtr, this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_BankBranchID_set(swigCPtr, this,
				value);
	}

	public String getBankBranchID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_BankBranchID_get(
				swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_BrokerID_get(swigCPtr,
				this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_BrokerBranchID_set(swigCPtr,
				this, value);
	}

	public String getBrokerBranchID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_BrokerBranchID_get(
				swigCPtr, this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_TradeDate_set(swigCPtr, this,
				value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_TradeDate_get(swigCPtr,
				this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_TradeTime_set(swigCPtr, this,
				value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_TradeTime_get(swigCPtr,
				this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_BankSerial_set(swigCPtr, this,
				value);
	}

	public String getBankSerial() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_BankSerial_get(swigCPtr,
				this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_TradingDay_set(swigCPtr, this,
				value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_TradingDay_get(swigCPtr,
				this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_PlateSerial_set(swigCPtr, this,
				value);
	}

	public int getPlateSerial() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_PlateSerial_get(swigCPtr,
				this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_LastFragment_set(swigCPtr, this,
				value);
	}

	public char getLastFragment() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_LastFragment_get(
				swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_SessionID_set(swigCPtr, this,
				value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_SessionID_get(swigCPtr,
				this);
	}

	public void setInstallID(int value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_InstallID_set(swigCPtr, this,
				value);
	}

	public int getInstallID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_InstallID_get(swigCPtr,
				this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI
				.CThostFtdcRspFutureSignOutField_UserID_get(swigCPtr, this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_Digest_set(swigCPtr, this, value);
	}

	public String getDigest() {
		return CtpJNI
				.CThostFtdcRspFutureSignOutField_Digest_get(swigCPtr, this);
	}

	public void setCurrencyID(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_CurrencyID_set(swigCPtr, this,
				value);
	}

	public String getCurrencyID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_CurrencyID_get(swigCPtr,
				this);
	}

	public void setDeviceID(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_DeviceID_set(swigCPtr, this,
				value);
	}

	public String getDeviceID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_DeviceID_get(swigCPtr,
				this);
	}

	public void setBrokerIDByBank(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_BrokerIDByBank_set(swigCPtr,
				this, value);
	}

	public String getBrokerIDByBank() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_BrokerIDByBank_get(
				swigCPtr, this);
	}

	public void setOperNo(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_OperNo_set(swigCPtr, this, value);
	}

	public String getOperNo() {
		return CtpJNI
				.CThostFtdcRspFutureSignOutField_OperNo_get(swigCPtr, this);
	}

	public void setRequestID(int value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_RequestID_set(swigCPtr, this,
				value);
	}

	public int getRequestID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_RequestID_get(swigCPtr,
				this);
	}

	public void setTID(int value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_TID_set(swigCPtr, this, value);
	}

	public int getTID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_TID_get(swigCPtr, this);
	}

	public void setErrorID(int value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_ErrorID_set(swigCPtr, this,
				value);
	}

	public int getErrorID() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_ErrorID_get(swigCPtr,
				this);
	}

	public void setErrorMsg(String value) {
		CtpJNI.CThostFtdcRspFutureSignOutField_ErrorMsg_set(swigCPtr, this,
				value);
	}

	public String getErrorMsg() {
		return CtpJNI.CThostFtdcRspFutureSignOutField_ErrorMsg_get(swigCPtr,
				this);
	}

	public CThostFtdcRspFutureSignOutField() {
		this(CtpJNI.new_CThostFtdcRspFutureSignOutField(), true);
	}

}
