/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcBrokerUserField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcBrokerUserField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcBrokerUserField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcBrokerUserField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcBrokerUserField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcBrokerUserField_BrokerID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcBrokerUserField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcBrokerUserField_UserID_get(swigCPtr, this);
	}

	public void setUserName(String value) {
		CtpJNI.CThostFtdcBrokerUserField_UserName_set(swigCPtr, this, value);
	}

	public String getUserName() {
		return CtpJNI.CThostFtdcBrokerUserField_UserName_get(swigCPtr, this);
	}

	public void setUserType(char value) {
		CtpJNI.CThostFtdcBrokerUserField_UserType_set(swigCPtr, this, value);
	}

	public char getUserType() {
		return CtpJNI.CThostFtdcBrokerUserField_UserType_get(swigCPtr, this);
	}

	public void setIsActive(int value) {
		CtpJNI.CThostFtdcBrokerUserField_IsActive_set(swigCPtr, this, value);
	}

	public int getIsActive() {
		return CtpJNI.CThostFtdcBrokerUserField_IsActive_get(swigCPtr, this);
	}

	public void setIsUsingOTP(int value) {
		CtpJNI.CThostFtdcBrokerUserField_IsUsingOTP_set(swigCPtr, this, value);
	}

	public int getIsUsingOTP() {
		return CtpJNI.CThostFtdcBrokerUserField_IsUsingOTP_get(swigCPtr, this);
	}

	public CThostFtdcBrokerUserField() {
		this(CtpJNI.new_CThostFtdcBrokerUserField(), true);
	}

}
