/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcReqUserLoginField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcReqUserLoginField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcReqUserLoginField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcReqUserLoginField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_TradingDay_set(swigCPtr, this, value);
	}

	public String getTradingDay() {
		return CtpJNI
				.CThostFtdcReqUserLoginField_TradingDay_get(swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcReqUserLoginField_BrokerID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcReqUserLoginField_UserID_get(swigCPtr, this);
	}

	public void setPassword(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_Password_set(swigCPtr, this, value);
	}

	public String getPassword() {
		return CtpJNI.CThostFtdcReqUserLoginField_Password_get(swigCPtr, this);
	}

	public void setUserProductInfo(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_UserProductInfo_set(swigCPtr, this,
				value);
	}

	public String getUserProductInfo() {
		return CtpJNI.CThostFtdcReqUserLoginField_UserProductInfo_get(swigCPtr,
				this);
	}

	public void setInterfaceProductInfo(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_InterfaceProductInfo_set(swigCPtr,
				this, value);
	}

	public String getInterfaceProductInfo() {
		return CtpJNI.CThostFtdcReqUserLoginField_InterfaceProductInfo_get(
				swigCPtr, this);
	}

	public void setProtocolInfo(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_ProtocolInfo_set(swigCPtr, this,
				value);
	}

	public String getProtocolInfo() {
		return CtpJNI.CThostFtdcReqUserLoginField_ProtocolInfo_get(swigCPtr,
				this);
	}

	public void setMacAddress(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_MacAddress_set(swigCPtr, this, value);
	}

	public String getMacAddress() {
		return CtpJNI
				.CThostFtdcReqUserLoginField_MacAddress_get(swigCPtr, this);
	}

	public void setOneTimePassword(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_OneTimePassword_set(swigCPtr, this,
				value);
	}

	public String getOneTimePassword() {
		return CtpJNI.CThostFtdcReqUserLoginField_OneTimePassword_get(swigCPtr,
				this);
	}

	public void setClientIPAddress(String value) {
		CtpJNI.CThostFtdcReqUserLoginField_ClientIPAddress_set(swigCPtr, this,
				value);
	}

	public String getClientIPAddress() {
		return CtpJNI.CThostFtdcReqUserLoginField_ClientIPAddress_get(swigCPtr,
				this);
	}

	public CThostFtdcReqUserLoginField() {
		this(CtpJNI.new_CThostFtdcReqUserLoginField(), true);
	}

}
