/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcCombinationLegField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcCombinationLegField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcCombinationLegField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcCombinationLegField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setCombInstrumentID(String value) {
		CtpJNI.CThostFtdcCombinationLegField_CombInstrumentID_set(swigCPtr,
				this, value);
	}

	public String getCombInstrumentID() {
		return CtpJNI.CThostFtdcCombinationLegField_CombInstrumentID_get(
				swigCPtr, this);
	}

	public void setLegID(int value) {
		CtpJNI.CThostFtdcCombinationLegField_LegID_set(swigCPtr, this, value);
	}

	public int getLegID() {
		return CtpJNI.CThostFtdcCombinationLegField_LegID_get(swigCPtr, this);
	}

	public void setLegInstrumentID(String value) {
		CtpJNI.CThostFtdcCombinationLegField_LegInstrumentID_set(swigCPtr,
				this, value);
	}

	public String getLegInstrumentID() {
		return CtpJNI.CThostFtdcCombinationLegField_LegInstrumentID_get(
				swigCPtr, this);
	}

	public void setDirection(char value) {
		CtpJNI.CThostFtdcCombinationLegField_Direction_set(swigCPtr, this,
				value);
	}

	public char getDirection() {
		return CtpJNI.CThostFtdcCombinationLegField_Direction_get(swigCPtr,
				this);
	}

	public void setLegMultiple(int value) {
		CtpJNI.CThostFtdcCombinationLegField_LegMultiple_set(swigCPtr, this,
				value);
	}

	public int getLegMultiple() {
		return CtpJNI.CThostFtdcCombinationLegField_LegMultiple_get(swigCPtr,
				this);
	}

	public void setImplyLevel(int value) {
		CtpJNI.CThostFtdcCombinationLegField_ImplyLevel_set(swigCPtr, this,
				value);
	}

	public int getImplyLevel() {
		return CtpJNI.CThostFtdcCombinationLegField_ImplyLevel_get(swigCPtr,
				this);
	}

	public CThostFtdcCombinationLegField() {
		this(CtpJNI.new_CThostFtdcCombinationLegField(), true);
	}

}
