/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcTradingAccountPasswordUpdateField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcTradingAccountPasswordUpdateField(long cPtr,
			boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(
			CThostFtdcTradingAccountPasswordUpdateField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcTradingAccountPasswordUpdateField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcTradingAccountPasswordUpdateField_BrokerID_set(
				swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcTradingAccountPasswordUpdateField_BrokerID_get(
				swigCPtr, this);
	}

	public void setAccountID(String value) {
		CtpJNI.CThostFtdcTradingAccountPasswordUpdateField_AccountID_set(
				swigCPtr, this, value);
	}

	public String getAccountID() {
		return CtpJNI
				.CThostFtdcTradingAccountPasswordUpdateField_AccountID_get(
						swigCPtr, this);
	}

	public void setOldPassword(String value) {
		CtpJNI.CThostFtdcTradingAccountPasswordUpdateField_OldPassword_set(
				swigCPtr, this, value);
	}

	public String getOldPassword() {
		return CtpJNI
				.CThostFtdcTradingAccountPasswordUpdateField_OldPassword_get(
						swigCPtr, this);
	}

	public void setNewPassword(String value) {
		CtpJNI.CThostFtdcTradingAccountPasswordUpdateField_NewPassword_set(
				swigCPtr, this, value);
	}

	public String getNewPassword() {
		return CtpJNI
				.CThostFtdcTradingAccountPasswordUpdateField_NewPassword_get(
						swigCPtr, this);
	}

	public CThostFtdcTradingAccountPasswordUpdateField() {
		this(CtpJNI.new_CThostFtdcTradingAccountPasswordUpdateField(), true);
	}

}
