/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQryCombinationLegField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQryCombinationLegField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQryCombinationLegField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQryCombinationLegField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setCombInstrumentID(String value) {
		CtpJNI.CThostFtdcQryCombinationLegField_CombInstrumentID_set(swigCPtr,
				this, value);
	}

	public String getCombInstrumentID() {
		return CtpJNI.CThostFtdcQryCombinationLegField_CombInstrumentID_get(
				swigCPtr, this);
	}

	public void setLegID(int value) {
		CtpJNI.CThostFtdcQryCombinationLegField_LegID_set(swigCPtr, this, value);
	}

	public int getLegID() {
		return CtpJNI
				.CThostFtdcQryCombinationLegField_LegID_get(swigCPtr, this);
	}

	public void setLegInstrumentID(String value) {
		CtpJNI.CThostFtdcQryCombinationLegField_LegInstrumentID_set(swigCPtr,
				this, value);
	}

	public String getLegInstrumentID() {
		return CtpJNI.CThostFtdcQryCombinationLegField_LegInstrumentID_get(
				swigCPtr, this);
	}

	public CThostFtdcQryCombinationLegField() {
		this(CtpJNI.new_CThostFtdcQryCombinationLegField(), true);
	}

}
