/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcReqTransferField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcReqTransferField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcReqTransferField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcReqTransferField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcReqTransferField_TradeCode_set(swigCPtr, this, value);
	}

	public String getTradeCode() {
		return CtpJNI.CThostFtdcReqTransferField_TradeCode_get(swigCPtr, this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcReqTransferField_BankID_set(swigCPtr, this, value);
	}

	public String getBankID() {
		return CtpJNI.CThostFtdcReqTransferField_BankID_get(swigCPtr, this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcReqTransferField_BankBranchID_set(swigCPtr, this,
				value);
	}

	public String getBankBranchID() {
		return CtpJNI.CThostFtdcReqTransferField_BankBranchID_get(swigCPtr,
				this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcReqTransferField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcReqTransferField_BrokerID_get(swigCPtr, this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcReqTransferField_BrokerBranchID_set(swigCPtr, this,
				value);
	}

	public String getBrokerBranchID() {
		return CtpJNI.CThostFtdcReqTransferField_BrokerBranchID_get(swigCPtr,
				this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcReqTransferField_TradeDate_set(swigCPtr, this, value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcReqTransferField_TradeDate_get(swigCPtr, this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcReqTransferField_TradeTime_set(swigCPtr, this, value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcReqTransferField_TradeTime_get(swigCPtr, this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcReqTransferField_BankSerial_set(swigCPtr, this, value);
	}

	public String getBankSerial() {
		return CtpJNI.CThostFtdcReqTransferField_BankSerial_get(swigCPtr, this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcReqTransferField_TradingDay_set(swigCPtr, this, value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcReqTransferField_TradingDay_get(swigCPtr, this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcReqTransferField_PlateSerial_set(swigCPtr, this, value);
	}

	public int getPlateSerial() {
		return CtpJNI
				.CThostFtdcReqTransferField_PlateSerial_get(swigCPtr, this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcReqTransferField_LastFragment_set(swigCPtr, this,
				value);
	}

	public char getLastFragment() {
		return CtpJNI.CThostFtdcReqTransferField_LastFragment_get(swigCPtr,
				this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcReqTransferField_SessionID_set(swigCPtr, this, value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcReqTransferField_SessionID_get(swigCPtr, this);
	}

	public void setCustomerName(String value) {
		CtpJNI.CThostFtdcReqTransferField_CustomerName_set(swigCPtr, this,
				value);
	}

	public String getCustomerName() {
		return CtpJNI.CThostFtdcReqTransferField_CustomerName_get(swigCPtr,
				this);
	}

	public void setIdCardType(char value) {
		CtpJNI.CThostFtdcReqTransferField_IdCardType_set(swigCPtr, this, value);
	}

	public char getIdCardType() {
		return CtpJNI.CThostFtdcReqTransferField_IdCardType_get(swigCPtr, this);
	}

	public void setIdentifiedCardNo(String value) {
		CtpJNI.CThostFtdcReqTransferField_IdentifiedCardNo_set(swigCPtr, this,
				value);
	}

	public String getIdentifiedCardNo() {
		return CtpJNI.CThostFtdcReqTransferField_IdentifiedCardNo_get(swigCPtr,
				this);
	}

	public void setCustType(char value) {
		CtpJNI.CThostFtdcReqTransferField_CustType_set(swigCPtr, this, value);
	}

	public char getCustType() {
		return CtpJNI.CThostFtdcReqTransferField_CustType_get(swigCPtr, this);
	}

	public void setBankAccount(String value) {
		CtpJNI.CThostFtdcReqTransferField_BankAccount_set(swigCPtr, this, value);
	}

	public String getBankAccount() {
		return CtpJNI
				.CThostFtdcReqTransferField_BankAccount_get(swigCPtr, this);
	}

	public void setBankPassWord(String value) {
		CtpJNI.CThostFtdcReqTransferField_BankPassWord_set(swigCPtr, this,
				value);
	}

	public String getBankPassWord() {
		return CtpJNI.CThostFtdcReqTransferField_BankPassWord_get(swigCPtr,
				this);
	}

	public void setAccountID(String value) {
		CtpJNI.CThostFtdcReqTransferField_AccountID_set(swigCPtr, this, value);
	}

	public String getAccountID() {
		return CtpJNI.CThostFtdcReqTransferField_AccountID_get(swigCPtr, this);
	}

	public void setPassword(String value) {
		CtpJNI.CThostFtdcReqTransferField_Password_set(swigCPtr, this, value);
	}

	public String getPassword() {
		return CtpJNI.CThostFtdcReqTransferField_Password_get(swigCPtr, this);
	}

	public void setInstallID(int value) {
		CtpJNI.CThostFtdcReqTransferField_InstallID_set(swigCPtr, this, value);
	}

	public int getInstallID() {
		return CtpJNI.CThostFtdcReqTransferField_InstallID_get(swigCPtr, this);
	}

	public void setFutureSerial(int value) {
		CtpJNI.CThostFtdcReqTransferField_FutureSerial_set(swigCPtr, this,
				value);
	}

	public int getFutureSerial() {
		return CtpJNI.CThostFtdcReqTransferField_FutureSerial_get(swigCPtr,
				this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcReqTransferField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcReqTransferField_UserID_get(swigCPtr, this);
	}

	public void setVerifyCertNoFlag(char value) {
		CtpJNI.CThostFtdcReqTransferField_VerifyCertNoFlag_set(swigCPtr, this,
				value);
	}

	public char getVerifyCertNoFlag() {
		return CtpJNI.CThostFtdcReqTransferField_VerifyCertNoFlag_get(swigCPtr,
				this);
	}

	public void setCurrencyID(String value) {
		CtpJNI.CThostFtdcReqTransferField_CurrencyID_set(swigCPtr, this, value);
	}

	public String getCurrencyID() {
		return CtpJNI.CThostFtdcReqTransferField_CurrencyID_get(swigCPtr, this);
	}

	public void setTradeAmount(double value) {
		CtpJNI.CThostFtdcReqTransferField_TradeAmount_set(swigCPtr, this, value);
	}

	public double getTradeAmount() {
		return CtpJNI
				.CThostFtdcReqTransferField_TradeAmount_get(swigCPtr, this);
	}

	public void setFutureFetchAmount(double value) {
		CtpJNI.CThostFtdcReqTransferField_FutureFetchAmount_set(swigCPtr, this,
				value);
	}

	public double getFutureFetchAmount() {
		return CtpJNI.CThostFtdcReqTransferField_FutureFetchAmount_get(
				swigCPtr, this);
	}

	public void setFeePayFlag(char value) {
		CtpJNI.CThostFtdcReqTransferField_FeePayFlag_set(swigCPtr, this, value);
	}

	public char getFeePayFlag() {
		return CtpJNI.CThostFtdcReqTransferField_FeePayFlag_get(swigCPtr, this);
	}

	public void setCustFee(double value) {
		CtpJNI.CThostFtdcReqTransferField_CustFee_set(swigCPtr, this, value);
	}

	public double getCustFee() {
		return CtpJNI.CThostFtdcReqTransferField_CustFee_get(swigCPtr, this);
	}

	public void setBrokerFee(double value) {
		CtpJNI.CThostFtdcReqTransferField_BrokerFee_set(swigCPtr, this, value);
	}

	public double getBrokerFee() {
		return CtpJNI.CThostFtdcReqTransferField_BrokerFee_get(swigCPtr, this);
	}

	public void setMessage(String value) {
		CtpJNI.CThostFtdcReqTransferField_Message_set(swigCPtr, this, value);
	}

	public String getMessage() {
		return CtpJNI.CThostFtdcReqTransferField_Message_get(swigCPtr, this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcReqTransferField_Digest_set(swigCPtr, this, value);
	}

	public String getDigest() {
		return CtpJNI.CThostFtdcReqTransferField_Digest_get(swigCPtr, this);
	}

	public void setBankAccType(char value) {
		CtpJNI.CThostFtdcReqTransferField_BankAccType_set(swigCPtr, this, value);
	}

	public char getBankAccType() {
		return CtpJNI
				.CThostFtdcReqTransferField_BankAccType_get(swigCPtr, this);
	}

	public void setDeviceID(String value) {
		CtpJNI.CThostFtdcReqTransferField_DeviceID_set(swigCPtr, this, value);
	}

	public String getDeviceID() {
		return CtpJNI.CThostFtdcReqTransferField_DeviceID_get(swigCPtr, this);
	}

	public void setBankSecuAccType(char value) {
		CtpJNI.CThostFtdcReqTransferField_BankSecuAccType_set(swigCPtr, this,
				value);
	}

	public char getBankSecuAccType() {
		return CtpJNI.CThostFtdcReqTransferField_BankSecuAccType_get(swigCPtr,
				this);
	}

	public void setBrokerIDByBank(String value) {
		CtpJNI.CThostFtdcReqTransferField_BrokerIDByBank_set(swigCPtr, this,
				value);
	}

	public String getBrokerIDByBank() {
		return CtpJNI.CThostFtdcReqTransferField_BrokerIDByBank_get(swigCPtr,
				this);
	}

	public void setBankSecuAcc(String value) {
		CtpJNI.CThostFtdcReqTransferField_BankSecuAcc_set(swigCPtr, this, value);
	}

	public String getBankSecuAcc() {
		return CtpJNI
				.CThostFtdcReqTransferField_BankSecuAcc_get(swigCPtr, this);
	}

	public void setBankPwdFlag(char value) {
		CtpJNI.CThostFtdcReqTransferField_BankPwdFlag_set(swigCPtr, this, value);
	}

	public char getBankPwdFlag() {
		return CtpJNI
				.CThostFtdcReqTransferField_BankPwdFlag_get(swigCPtr, this);
	}

	public void setSecuPwdFlag(char value) {
		CtpJNI.CThostFtdcReqTransferField_SecuPwdFlag_set(swigCPtr, this, value);
	}

	public char getSecuPwdFlag() {
		return CtpJNI
				.CThostFtdcReqTransferField_SecuPwdFlag_get(swigCPtr, this);
	}

	public void setOperNo(String value) {
		CtpJNI.CThostFtdcReqTransferField_OperNo_set(swigCPtr, this, value);
	}

	public String getOperNo() {
		return CtpJNI.CThostFtdcReqTransferField_OperNo_get(swigCPtr, this);
	}

	public void setRequestID(int value) {
		CtpJNI.CThostFtdcReqTransferField_RequestID_set(swigCPtr, this, value);
	}

	public int getRequestID() {
		return CtpJNI.CThostFtdcReqTransferField_RequestID_get(swigCPtr, this);
	}

	public void setTID(int value) {
		CtpJNI.CThostFtdcReqTransferField_TID_set(swigCPtr, this, value);
	}

	public int getTID() {
		return CtpJNI.CThostFtdcReqTransferField_TID_get(swigCPtr, this);
	}

	public void setTransferStatus(char value) {
		CtpJNI.CThostFtdcReqTransferField_TransferStatus_set(swigCPtr, this,
				value);
	}

	public char getTransferStatus() {
		return CtpJNI.CThostFtdcReqTransferField_TransferStatus_get(swigCPtr,
				this);
	}

	public CThostFtdcReqTransferField() {
		this(CtpJNI.new_CThostFtdcReqTransferField(), true);
	}

}
