/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQryMDTraderOfferField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQryMDTraderOfferField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQryMDTraderOfferField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQryMDTraderOfferField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcQryMDTraderOfferField_ExchangeID_set(swigCPtr, this,
				value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcQryMDTraderOfferField_ExchangeID_get(swigCPtr,
				this);
	}

	public void setParticipantID(String value) {
		CtpJNI.CThostFtdcQryMDTraderOfferField_ParticipantID_set(swigCPtr,
				this, value);
	}

	public String getParticipantID() {
		return CtpJNI.CThostFtdcQryMDTraderOfferField_ParticipantID_get(
				swigCPtr, this);
	}

	public void setTraderID(String value) {
		CtpJNI.CThostFtdcQryMDTraderOfferField_TraderID_set(swigCPtr, this,
				value);
	}

	public String getTraderID() {
		return CtpJNI.CThostFtdcQryMDTraderOfferField_TraderID_get(swigCPtr,
				this);
	}

	public CThostFtdcQryMDTraderOfferField() {
		this(CtpJNI.new_CThostFtdcQryMDTraderOfferField(), true);
	}

}
