/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcCommRateModelField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcCommRateModelField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcCommRateModelField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcCommRateModelField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcCommRateModelField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcCommRateModelField_BrokerID_get(swigCPtr, this);
	}

	public void setCommModelID(String value) {
		CtpJNI.CThostFtdcCommRateModelField_CommModelID_set(swigCPtr, this,
				value);
	}

	public String getCommModelID() {
		return CtpJNI.CThostFtdcCommRateModelField_CommModelID_get(swigCPtr,
				this);
	}

	public void setCommModelName(String value) {
		CtpJNI.CThostFtdcCommRateModelField_CommModelName_set(swigCPtr, this,
				value);
	}

	public String getCommModelName() {
		return CtpJNI.CThostFtdcCommRateModelField_CommModelName_get(swigCPtr,
				this);
	}

	public CThostFtdcCommRateModelField() {
		this(CtpJNI.new_CThostFtdcCommRateModelField(), true);
	}

}
