/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcInvestorAccountField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcInvestorAccountField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcInvestorAccountField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcInvestorAccountField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcInvestorAccountField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcInvestorAccountField_BrokerID_get(swigCPtr,
				this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcInvestorAccountField_InvestorID_set(swigCPtr, this,
				value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcInvestorAccountField_InvestorID_get(swigCPtr,
				this);
	}

	public void setAccountID(String value) {
		CtpJNI.CThostFtdcInvestorAccountField_AccountID_set(swigCPtr, this,
				value);
	}

	public String getAccountID() {
		return CtpJNI.CThostFtdcInvestorAccountField_AccountID_get(swigCPtr,
				this);
	}

	public CThostFtdcInvestorAccountField() {
		this(CtpJNI.new_CThostFtdcInvestorAccountField(), true);
	}

}
