/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcTraderSpi {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcTraderSpi(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcTraderSpi obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcTraderSpi(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	protected void swigDirectorDisconnect() {
		swigCMemOwn = false;
		delete();
	}

	public void swigReleaseOwnership() {
		swigCMemOwn = false;
		CtpJNI.CThostFtdcTraderSpi_change_ownership(this, swigCPtr, false);
	}

	public void swigTakeOwnership() {
		swigCMemOwn = true;
		CtpJNI.CThostFtdcTraderSpi_change_ownership(this, swigCPtr, true);
	}

	public void onFrontConnected() {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onFrontConnected(swigCPtr, this);
		else
			CtpJNI.CThostFtdcTraderSpi_onFrontConnectedSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this);
	}

	public void onFrontDisconnected(int nReason) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onFrontDisconnected(swigCPtr, this,
					nReason);
		else
			CtpJNI.CThostFtdcTraderSpi_onFrontDisconnectedSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, nReason);
	}

	public void onHeartBeatWarning(int nTimeLapse) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onHeartBeatWarning(swigCPtr, this,
					nTimeLapse);
		else
			CtpJNI.CThostFtdcTraderSpi_onHeartBeatWarningSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, nTimeLapse);
	}

	public void onRspAuthenticate(
			CThostFtdcRspAuthenticateField pRspAuthenticateField,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspAuthenticate(swigCPtr, this,
					CThostFtdcRspAuthenticateField
							.getCPtr(pRspAuthenticateField),
					pRspAuthenticateField, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspAuthenticateSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcRspAuthenticateField
							.getCPtr(pRspAuthenticateField),
					pRspAuthenticateField, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspUserLogin(CThostFtdcRspUserLoginField pRspUserLogin,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspUserLogin(swigCPtr, this,
					CThostFtdcRspUserLoginField.getCPtr(pRspUserLogin),
					pRspUserLogin, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspUserLoginSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspUserLoginField.getCPtr(pRspUserLogin),
					pRspUserLogin, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspUserLogout(CThostFtdcUserLogoutField pUserLogout,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspUserLogout(swigCPtr, this,
					CThostFtdcUserLogoutField.getCPtr(pUserLogout),
					pUserLogout, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspUserLogoutSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcUserLogoutField.getCPtr(pUserLogout),
					pUserLogout, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspUserPasswordUpdate(
			CThostFtdcUserPasswordUpdateField pUserPasswordUpdate,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspUserPasswordUpdate(swigCPtr, this,
					CThostFtdcUserPasswordUpdateField
							.getCPtr(pUserPasswordUpdate), pUserPasswordUpdate,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspUserPasswordUpdateSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcUserPasswordUpdateField
							.getCPtr(pUserPasswordUpdate), pUserPasswordUpdate,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspTradingAccountPasswordUpdate(
			CThostFtdcTradingAccountPasswordUpdateField pTradingAccountPasswordUpdate,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspTradingAccountPasswordUpdate(
					swigCPtr, this, CThostFtdcTradingAccountPasswordUpdateField
							.getCPtr(pTradingAccountPasswordUpdate),
					pTradingAccountPasswordUpdate, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspTradingAccountPasswordUpdateSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcTradingAccountPasswordUpdateField
							.getCPtr(pTradingAccountPasswordUpdate),
					pTradingAccountPasswordUpdate, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspOrderInsert(CThostFtdcInputOrderField pInputOrder,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspOrderInsert(swigCPtr, this,
					CThostFtdcInputOrderField.getCPtr(pInputOrder),
					pInputOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspOrderInsertSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcInputOrderField.getCPtr(pInputOrder),
					pInputOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspParkedOrderInsert(CThostFtdcParkedOrderField pParkedOrder,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspParkedOrderInsert(swigCPtr, this,
					CThostFtdcParkedOrderField.getCPtr(pParkedOrder),
					pParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspParkedOrderInsertSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcParkedOrderField.getCPtr(pParkedOrder),
					pParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspParkedOrderAction(
			CThostFtdcParkedOrderActionField pParkedOrderAction,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspParkedOrderAction(swigCPtr, this,
					CThostFtdcParkedOrderActionField
							.getCPtr(pParkedOrderAction), pParkedOrderAction,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspParkedOrderActionSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcParkedOrderActionField
							.getCPtr(pParkedOrderAction), pParkedOrderAction,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspOrderAction(
			CThostFtdcInputOrderActionField pInputOrderAction,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspOrderAction(swigCPtr, this,
					CThostFtdcInputOrderActionField.getCPtr(pInputOrderAction),
					pInputOrderAction,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspOrderActionSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcInputOrderActionField.getCPtr(pInputOrderAction),
					pInputOrderAction,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspQueryMaxOrderVolume(
			CThostFtdcQueryMaxOrderVolumeField pQueryMaxOrderVolume,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQueryMaxOrderVolume(swigCPtr, this,
					CThostFtdcQueryMaxOrderVolumeField
							.getCPtr(pQueryMaxOrderVolume),
					pQueryMaxOrderVolume, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQueryMaxOrderVolumeSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcQueryMaxOrderVolumeField
							.getCPtr(pQueryMaxOrderVolume),
					pQueryMaxOrderVolume, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspSettlementInfoConfirm(
			CThostFtdcSettlementInfoConfirmField pSettlementInfoConfirm,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspSettlementInfoConfirm(swigCPtr,
					this, CThostFtdcSettlementInfoConfirmField
							.getCPtr(pSettlementInfoConfirm),
					pSettlementInfoConfirm, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspSettlementInfoConfirmSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcSettlementInfoConfirmField
							.getCPtr(pSettlementInfoConfirm),
					pSettlementInfoConfirm, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspRemoveParkedOrder(
			CThostFtdcRemoveParkedOrderField pRemoveParkedOrder,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspRemoveParkedOrder(swigCPtr, this,
					CThostFtdcRemoveParkedOrderField
							.getCPtr(pRemoveParkedOrder), pRemoveParkedOrder,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspRemoveParkedOrderSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcRemoveParkedOrderField
							.getCPtr(pRemoveParkedOrder), pRemoveParkedOrder,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspRemoveParkedOrderAction(
			CThostFtdcRemoveParkedOrderActionField pRemoveParkedOrderAction,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspRemoveParkedOrderAction(swigCPtr,
					this, CThostFtdcRemoveParkedOrderActionField
							.getCPtr(pRemoveParkedOrderAction),
					pRemoveParkedOrderAction, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspRemoveParkedOrderActionSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcRemoveParkedOrderActionField
							.getCPtr(pRemoveParkedOrderAction),
					pRemoveParkedOrderAction, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryOrder(CThostFtdcOrderField pOrder,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryOrder(swigCPtr, this,
					CThostFtdcOrderField.getCPtr(pOrder), pOrder,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryOrderSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcOrderField.getCPtr(pOrder),
					pOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspQryTrade(CThostFtdcTradeField pTrade,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryTrade(swigCPtr, this,
					CThostFtdcTradeField.getCPtr(pTrade), pTrade,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryTradeSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcTradeField.getCPtr(pTrade),
					pTrade, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspQryInvestorPosition(
			CThostFtdcInvestorPositionField pInvestorPosition,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorPosition(swigCPtr, this,
					CThostFtdcInvestorPositionField.getCPtr(pInvestorPosition),
					pInvestorPosition,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorPositionSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcInvestorPositionField.getCPtr(pInvestorPosition),
					pInvestorPosition,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspQryTradingAccount(
			CThostFtdcTradingAccountField pTradingAccount,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryTradingAccount(swigCPtr, this,
					CThostFtdcTradingAccountField.getCPtr(pTradingAccount),
					pTradingAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryTradingAccountSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcTradingAccountField.getCPtr(pTradingAccount),
					pTradingAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryInvestor(CThostFtdcInvestorField pInvestor,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestor(swigCPtr, this,
					CThostFtdcInvestorField.getCPtr(pInvestor), pInvestor,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcInvestorField.getCPtr(pInvestor),
					pInvestor, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryTradingCode(CThostFtdcTradingCodeField pTradingCode,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryTradingCode(swigCPtr, this,
					CThostFtdcTradingCodeField.getCPtr(pTradingCode),
					pTradingCode, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryTradingCodeSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcTradingCodeField.getCPtr(pTradingCode),
					pTradingCode, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryInstrumentMarginRate(
			CThostFtdcInstrumentMarginRateField pInstrumentMarginRate,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryInstrumentMarginRate(swigCPtr,
					this, CThostFtdcInstrumentMarginRateField
							.getCPtr(pInstrumentMarginRate),
					pInstrumentMarginRate, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryInstrumentMarginRateSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcInstrumentMarginRateField
							.getCPtr(pInstrumentMarginRate),
					pInstrumentMarginRate, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryInstrumentCommissionRate(
			CThostFtdcInstrumentCommissionRateField pInstrumentCommissionRate,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryInstrumentCommissionRate(
					swigCPtr, this, CThostFtdcInstrumentCommissionRateField
							.getCPtr(pInstrumentCommissionRate),
					pInstrumentCommissionRate, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryInstrumentCommissionRateSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcInstrumentCommissionRateField
							.getCPtr(pInstrumentCommissionRate),
					pInstrumentCommissionRate, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryExchange(CThostFtdcExchangeField pExchange,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryExchange(swigCPtr, this,
					CThostFtdcExchangeField.getCPtr(pExchange), pExchange,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryExchangeSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcExchangeField.getCPtr(pExchange),
					pExchange, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryInstrument(CThostFtdcInstrumentField pInstrument,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryInstrument(swigCPtr, this,
					CThostFtdcInstrumentField.getCPtr(pInstrument),
					pInstrument, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryInstrumentSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcInstrumentField.getCPtr(pInstrument),
					pInstrument, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryDepthMarketData(
			CThostFtdcDepthMarketDataField pDepthMarketData,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryDepthMarketData(swigCPtr, this,
					CThostFtdcDepthMarketDataField.getCPtr(pDepthMarketData),
					pDepthMarketData, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryDepthMarketDataSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcDepthMarketDataField.getCPtr(pDepthMarketData),
					pDepthMarketData, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQrySettlementInfo(
			CThostFtdcSettlementInfoField pSettlementInfo,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQrySettlementInfo(swigCPtr, this,
					CThostFtdcSettlementInfoField.getCPtr(pSettlementInfo),
					pSettlementInfo, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQrySettlementInfoSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcSettlementInfoField.getCPtr(pSettlementInfo),
					pSettlementInfo, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryTransferBank(CThostFtdcTransferBankField pTransferBank,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryTransferBank(swigCPtr, this,
					CThostFtdcTransferBankField.getCPtr(pTransferBank),
					pTransferBank, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryTransferBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcTransferBankField.getCPtr(pTransferBank),
					pTransferBank, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryInvestorPositionDetail(
			CThostFtdcInvestorPositionDetailField pInvestorPositionDetail,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorPositionDetail(swigCPtr,
					this, CThostFtdcInvestorPositionDetailField
							.getCPtr(pInvestorPositionDetail),
					pInvestorPositionDetail, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorPositionDetailSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcInvestorPositionDetailField
							.getCPtr(pInvestorPositionDetail),
					pInvestorPositionDetail, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryNotice(CThostFtdcNoticeField pNotice,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryNotice(swigCPtr, this,
					CThostFtdcNoticeField.getCPtr(pNotice), pNotice,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryNoticeSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcNoticeField.getCPtr(pNotice),
					pNotice, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQrySettlementInfoConfirm(
			CThostFtdcSettlementInfoConfirmField pSettlementInfoConfirm,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQrySettlementInfoConfirm(swigCPtr,
					this, CThostFtdcSettlementInfoConfirmField
							.getCPtr(pSettlementInfoConfirm),
					pSettlementInfoConfirm, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQrySettlementInfoConfirmSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcSettlementInfoConfirmField
							.getCPtr(pSettlementInfoConfirm),
					pSettlementInfoConfirm, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryInvestorPositionCombineDetail(
			CThostFtdcInvestorPositionCombineDetailField pInvestorPositionCombineDetail,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorPositionCombineDetail(
					swigCPtr, this,
					CThostFtdcInvestorPositionCombineDetailField
							.getCPtr(pInvestorPositionCombineDetail),
					pInvestorPositionCombineDetail, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorPositionCombineDetailSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcInvestorPositionCombineDetailField
							.getCPtr(pInvestorPositionCombineDetail),
					pInvestorPositionCombineDetail, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryCFMMCTradingAccountKey(
			CThostFtdcCFMMCTradingAccountKeyField pCFMMCTradingAccountKey,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryCFMMCTradingAccountKey(swigCPtr,
					this, CThostFtdcCFMMCTradingAccountKeyField
							.getCPtr(pCFMMCTradingAccountKey),
					pCFMMCTradingAccountKey, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryCFMMCTradingAccountKeySwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcCFMMCTradingAccountKeyField
							.getCPtr(pCFMMCTradingAccountKey),
					pCFMMCTradingAccountKey, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryEWarrantOffset(
			CThostFtdcEWarrantOffsetField pEWarrantOffset,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryEWarrantOffset(swigCPtr, this,
					CThostFtdcEWarrantOffsetField.getCPtr(pEWarrantOffset),
					pEWarrantOffset, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryEWarrantOffsetSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcEWarrantOffsetField.getCPtr(pEWarrantOffset),
					pEWarrantOffset, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryInvestorProductGroupMargin(
			CThostFtdcInvestorProductGroupMarginField pInvestorProductGroupMargin,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorProductGroupMargin(
					swigCPtr, this, CThostFtdcInvestorProductGroupMarginField
							.getCPtr(pInvestorProductGroupMargin),
					pInvestorProductGroupMargin, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryInvestorProductGroupMarginSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcInvestorProductGroupMarginField
							.getCPtr(pInvestorProductGroupMargin),
					pInvestorProductGroupMargin, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryExchangeMarginRate(
			CThostFtdcExchangeMarginRateField pExchangeMarginRate,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryExchangeMarginRate(swigCPtr,
					this, CThostFtdcExchangeMarginRateField
							.getCPtr(pExchangeMarginRate), pExchangeMarginRate,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryExchangeMarginRateSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcExchangeMarginRateField
							.getCPtr(pExchangeMarginRate), pExchangeMarginRate,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspQryExchangeMarginRateAdjust(
			CThostFtdcExchangeMarginRateAdjustField pExchangeMarginRateAdjust,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryExchangeMarginRateAdjust(
					swigCPtr, this, CThostFtdcExchangeMarginRateAdjustField
							.getCPtr(pExchangeMarginRateAdjust),
					pExchangeMarginRateAdjust, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryExchangeMarginRateAdjustSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcExchangeMarginRateAdjustField
							.getCPtr(pExchangeMarginRateAdjust),
					pExchangeMarginRateAdjust, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryTransferSerial(
			CThostFtdcTransferSerialField pTransferSerial,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryTransferSerial(swigCPtr, this,
					CThostFtdcTransferSerialField.getCPtr(pTransferSerial),
					pTransferSerial, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryTransferSerialSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcTransferSerialField.getCPtr(pTransferSerial),
					pTransferSerial, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryAccountregister(
			CThostFtdcAccountregisterField pAccountregister,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryAccountregister(swigCPtr, this,
					CThostFtdcAccountregisterField.getCPtr(pAccountregister),
					pAccountregister, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryAccountregisterSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcAccountregisterField.getCPtr(pAccountregister),
					pAccountregister, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspError(CThostFtdcRspInfoField pRspInfo, int nRequestID,
			boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspError(swigCPtr, this,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspErrorSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRtnOrder(CThostFtdcOrderField pOrder) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnOrder(swigCPtr, this,
					CThostFtdcOrderField.getCPtr(pOrder), pOrder);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnOrderSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcOrderField.getCPtr(pOrder),
					pOrder);
	}

	public void onRtnTrade(CThostFtdcTradeField pTrade) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnTrade(swigCPtr, this,
					CThostFtdcTradeField.getCPtr(pTrade), pTrade);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnTradeSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcTradeField.getCPtr(pTrade),
					pTrade);
	}

	public void onErrRtnOrderInsert(CThostFtdcInputOrderField pInputOrder,
			CThostFtdcRspInfoField pRspInfo) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onErrRtnOrderInsert(swigCPtr, this,
					CThostFtdcInputOrderField.getCPtr(pInputOrder),
					pInputOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
		else
			CtpJNI.CThostFtdcTraderSpi_onErrRtnOrderInsertSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcInputOrderField.getCPtr(pInputOrder),
					pInputOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
	}

	public void onErrRtnOrderAction(CThostFtdcOrderActionField pOrderAction,
			CThostFtdcRspInfoField pRspInfo) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onErrRtnOrderAction(swigCPtr, this,
					CThostFtdcOrderActionField.getCPtr(pOrderAction),
					pOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
		else
			CtpJNI.CThostFtdcTraderSpi_onErrRtnOrderActionSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcOrderActionField.getCPtr(pOrderAction),
					pOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
	}

	public void onRtnInstrumentStatus(
			CThostFtdcInstrumentStatusField pInstrumentStatus) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnInstrumentStatus(swigCPtr, this,
					CThostFtdcInstrumentStatusField.getCPtr(pInstrumentStatus),
					pInstrumentStatus);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnInstrumentStatusSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcInstrumentStatusField.getCPtr(pInstrumentStatus),
					pInstrumentStatus);
	}

	public void onRtnTradingNotice(
			CThostFtdcTradingNoticeInfoField pTradingNoticeInfo) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnTradingNotice(swigCPtr, this,
					CThostFtdcTradingNoticeInfoField
							.getCPtr(pTradingNoticeInfo), pTradingNoticeInfo);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnTradingNoticeSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcTradingNoticeInfoField
							.getCPtr(pTradingNoticeInfo), pTradingNoticeInfo);
	}

	public void onRtnErrorConditionalOrder(
			CThostFtdcErrorConditionalOrderField pErrorConditionalOrder) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnErrorConditionalOrder(swigCPtr,
					this, CThostFtdcErrorConditionalOrderField
							.getCPtr(pErrorConditionalOrder),
					pErrorConditionalOrder);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnErrorConditionalOrderSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcErrorConditionalOrderField
							.getCPtr(pErrorConditionalOrder),
					pErrorConditionalOrder);
	}

	public void onRspQryContractBank(CThostFtdcContractBankField pContractBank,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryContractBank(swigCPtr, this,
					CThostFtdcContractBankField.getCPtr(pContractBank),
					pContractBank, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryContractBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcContractBankField.getCPtr(pContractBank),
					pContractBank, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryParkedOrder(CThostFtdcParkedOrderField pParkedOrder,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryParkedOrder(swigCPtr, this,
					CThostFtdcParkedOrderField.getCPtr(pParkedOrder),
					pParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryParkedOrderSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcParkedOrderField.getCPtr(pParkedOrder),
					pParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryParkedOrderAction(
			CThostFtdcParkedOrderActionField pParkedOrderAction,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryParkedOrderAction(swigCPtr,
					this, CThostFtdcParkedOrderActionField
							.getCPtr(pParkedOrderAction), pParkedOrderAction,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryParkedOrderActionSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcParkedOrderActionField
							.getCPtr(pParkedOrderAction), pParkedOrderAction,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRspQryTradingNotice(
			CThostFtdcTradingNoticeField pTradingNotice,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryTradingNotice(swigCPtr, this,
					CThostFtdcTradingNoticeField.getCPtr(pTradingNotice),
					pTradingNotice, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryTradingNoticeSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcTradingNoticeField.getCPtr(pTradingNotice),
					pTradingNotice, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryBrokerTradingParams(
			CThostFtdcBrokerTradingParamsField pBrokerTradingParams,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryBrokerTradingParams(swigCPtr,
					this, CThostFtdcBrokerTradingParamsField
							.getCPtr(pBrokerTradingParams),
					pBrokerTradingParams, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryBrokerTradingParamsSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcBrokerTradingParamsField
							.getCPtr(pBrokerTradingParams),
					pBrokerTradingParams, CThostFtdcRspInfoField
							.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQryBrokerTradingAlgos(
			CThostFtdcBrokerTradingAlgosField pBrokerTradingAlgos,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQryBrokerTradingAlgos(swigCPtr,
					this, CThostFtdcBrokerTradingAlgosField
							.getCPtr(pBrokerTradingAlgos), pBrokerTradingAlgos,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQryBrokerTradingAlgosSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcBrokerTradingAlgosField
							.getCPtr(pBrokerTradingAlgos), pBrokerTradingAlgos,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo,
					nRequestID, bIsLast);
	}

	public void onRtnFromBankToFutureByBank(
			CThostFtdcRspTransferField pRspTransfer) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnFromBankToFutureByBank(swigCPtr,
					this, CThostFtdcRspTransferField.getCPtr(pRspTransfer),
					pRspTransfer);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnFromBankToFutureByBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspTransferField.getCPtr(pRspTransfer),
					pRspTransfer);
	}

	public void onRtnFromFutureToBankByBank(
			CThostFtdcRspTransferField pRspTransfer) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnFromFutureToBankByBank(swigCPtr,
					this, CThostFtdcRspTransferField.getCPtr(pRspTransfer),
					pRspTransfer);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnFromFutureToBankByBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspTransferField.getCPtr(pRspTransfer),
					pRspTransfer);
	}

	public void onRtnRepealFromBankToFutureByBank(
			CThostFtdcRspRepealField pRspRepeal) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromBankToFutureByBank(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromBankToFutureByBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
	}

	public void onRtnRepealFromFutureToBankByBank(
			CThostFtdcRspRepealField pRspRepeal) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromFutureToBankByBank(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromFutureToBankByBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
	}

	public void onRtnFromBankToFutureByFuture(
			CThostFtdcRspTransferField pRspTransfer) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnFromBankToFutureByFuture(swigCPtr,
					this, CThostFtdcRspTransferField.getCPtr(pRspTransfer),
					pRspTransfer);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnFromBankToFutureByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspTransferField.getCPtr(pRspTransfer),
					pRspTransfer);
	}

	public void onRtnFromFutureToBankByFuture(
			CThostFtdcRspTransferField pRspTransfer) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnFromFutureToBankByFuture(swigCPtr,
					this, CThostFtdcRspTransferField.getCPtr(pRspTransfer),
					pRspTransfer);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnFromFutureToBankByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspTransferField.getCPtr(pRspTransfer),
					pRspTransfer);
	}

	public void onRtnRepealFromBankToFutureByFutureManual(
			CThostFtdcRspRepealField pRspRepeal) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromBankToFutureByFutureManual(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromBankToFutureByFutureManualSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
	}

	public void onRtnRepealFromFutureToBankByFutureManual(
			CThostFtdcRspRepealField pRspRepeal) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromFutureToBankByFutureManual(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromFutureToBankByFutureManualSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
	}

	public void onRtnQueryBankBalanceByFuture(
			CThostFtdcNotifyQueryAccountField pNotifyQueryAccount) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnQueryBankBalanceByFuture(swigCPtr,
					this, CThostFtdcNotifyQueryAccountField
							.getCPtr(pNotifyQueryAccount), pNotifyQueryAccount);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnQueryBankBalanceByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this, CThostFtdcNotifyQueryAccountField
							.getCPtr(pNotifyQueryAccount), pNotifyQueryAccount);
	}

	public void onErrRtnBankToFutureByFuture(
			CThostFtdcReqTransferField pReqTransfer,
			CThostFtdcRspInfoField pRspInfo) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onErrRtnBankToFutureByFuture(swigCPtr,
					this, CThostFtdcReqTransferField.getCPtr(pReqTransfer),
					pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
		else
			CtpJNI.CThostFtdcTraderSpi_onErrRtnBankToFutureByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcReqTransferField.getCPtr(pReqTransfer),
					pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
	}

	public void onErrRtnFutureToBankByFuture(
			CThostFtdcReqTransferField pReqTransfer,
			CThostFtdcRspInfoField pRspInfo) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onErrRtnFutureToBankByFuture(swigCPtr,
					this, CThostFtdcReqTransferField.getCPtr(pReqTransfer),
					pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
		else
			CtpJNI.CThostFtdcTraderSpi_onErrRtnFutureToBankByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcReqTransferField.getCPtr(pReqTransfer),
					pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
	}

	public void onErrRtnRepealBankToFutureByFutureManual(
			CThostFtdcReqRepealField pReqRepeal, CThostFtdcRspInfoField pRspInfo) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onErrRtnRepealBankToFutureByFutureManual(
					swigCPtr, this,
					CThostFtdcReqRepealField.getCPtr(pReqRepeal), pReqRepeal,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
		else
			CtpJNI.CThostFtdcTraderSpi_onErrRtnRepealBankToFutureByFutureManualSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcReqRepealField.getCPtr(pReqRepeal), pReqRepeal,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
	}

	public void onErrRtnRepealFutureToBankByFutureManual(
			CThostFtdcReqRepealField pReqRepeal, CThostFtdcRspInfoField pRspInfo) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onErrRtnRepealFutureToBankByFutureManual(
					swigCPtr, this,
					CThostFtdcReqRepealField.getCPtr(pReqRepeal), pReqRepeal,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
		else
			CtpJNI.CThostFtdcTraderSpi_onErrRtnRepealFutureToBankByFutureManualSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcReqRepealField.getCPtr(pReqRepeal), pReqRepeal,
					CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
	}

	public void onErrRtnQueryBankBalanceByFuture(
			CThostFtdcReqQueryAccountField pReqQueryAccount,
			CThostFtdcRspInfoField pRspInfo) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onErrRtnQueryBankBalanceByFuture(
					swigCPtr, this,
					CThostFtdcReqQueryAccountField.getCPtr(pReqQueryAccount),
					pReqQueryAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
		else
			CtpJNI.CThostFtdcTraderSpi_onErrRtnQueryBankBalanceByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcReqQueryAccountField.getCPtr(pReqQueryAccount),
					pReqQueryAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo);
	}

	public void onRtnRepealFromBankToFutureByFuture(
			CThostFtdcRspRepealField pRspRepeal) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromBankToFutureByFuture(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromBankToFutureByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
	}

	public void onRtnRepealFromFutureToBankByFuture(
			CThostFtdcRspRepealField pRspRepeal) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromFutureToBankByFuture(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnRepealFromFutureToBankByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
	}

	public void onRspFromBankToFutureByFuture(
			CThostFtdcReqTransferField pReqTransfer,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspFromBankToFutureByFuture(swigCPtr,
					this, CThostFtdcReqTransferField.getCPtr(pReqTransfer),
					pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspFromBankToFutureByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcReqTransferField.getCPtr(pReqTransfer),
					pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspFromFutureToBankByFuture(
			CThostFtdcReqTransferField pReqTransfer,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspFromFutureToBankByFuture(swigCPtr,
					this, CThostFtdcReqTransferField.getCPtr(pReqTransfer),
					pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspFromFutureToBankByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcReqTransferField.getCPtr(pReqTransfer),
					pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRspQueryBankAccountMoneyByFuture(
			CThostFtdcReqQueryAccountField pReqQueryAccount,
			CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRspQueryBankAccountMoneyByFuture(
					swigCPtr, this,
					CThostFtdcReqQueryAccountField.getCPtr(pReqQueryAccount),
					pReqQueryAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
		else
			CtpJNI.CThostFtdcTraderSpi_onRspQueryBankAccountMoneyByFutureSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcReqQueryAccountField.getCPtr(pReqQueryAccount),
					pReqQueryAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo),
					pRspInfo, nRequestID, bIsLast);
	}

	public void onRtnOpenAccountByBank(CThostFtdcOpenAccountField pOpenAccount) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnOpenAccountByBank(swigCPtr, this,
					CThostFtdcOpenAccountField.getCPtr(pOpenAccount),
					pOpenAccount);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnOpenAccountByBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcOpenAccountField.getCPtr(pOpenAccount),
					pOpenAccount);
	}

	public void onRtnCancelAccountByBank(
			CThostFtdcCancelAccountField pCancelAccount) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnCancelAccountByBank(swigCPtr, this,
					CThostFtdcCancelAccountField.getCPtr(pCancelAccount),
					pCancelAccount);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnCancelAccountByBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcCancelAccountField.getCPtr(pCancelAccount),
					pCancelAccount);
	}

	public void onRtnChangeAccountByBank(
			CThostFtdcChangeAccountField pChangeAccount) {
		if (getClass() == CThostFtdcTraderSpi.class)
			CtpJNI.CThostFtdcTraderSpi_onRtnChangeAccountByBank(swigCPtr, this,
					CThostFtdcChangeAccountField.getCPtr(pChangeAccount),
					pChangeAccount);
		else
			CtpJNI.CThostFtdcTraderSpi_onRtnChangeAccountByBankSwigExplicitCThostFtdcTraderSpi(
					swigCPtr, this,
					CThostFtdcChangeAccountField.getCPtr(pChangeAccount),
					pChangeAccount);
	}

	public CThostFtdcTraderSpi() {
		this(CtpJNI.new_CThostFtdcTraderSpi(), true);
		CtpJNI.CThostFtdcTraderSpi_director_connect(this, swigCPtr,
				swigCMemOwn, true);
	}

}
