/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcInstrumentTradingRightField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcInstrumentTradingRightField(long cPtr,
			boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcInstrumentTradingRightField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcInstrumentTradingRightField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcInstrumentTradingRightField_InstrumentID_set(swigCPtr,
				this, value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcInstrumentTradingRightField_InstrumentID_get(
				swigCPtr, this);
	}

	public void setInvestorRange(char value) {
		CtpJNI.CThostFtdcInstrumentTradingRightField_InvestorRange_set(
				swigCPtr, this, value);
	}

	public char getInvestorRange() {
		return CtpJNI.CThostFtdcInstrumentTradingRightField_InvestorRange_get(
				swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcInstrumentTradingRightField_BrokerID_set(swigCPtr,
				this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcInstrumentTradingRightField_BrokerID_get(
				swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcInstrumentTradingRightField_InvestorID_set(swigCPtr,
				this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcInstrumentTradingRightField_InvestorID_get(
				swigCPtr, this);
	}

	public void setTradingRight(char value) {
		CtpJNI.CThostFtdcInstrumentTradingRightField_TradingRight_set(swigCPtr,
				this, value);
	}

	public char getTradingRight() {
		return CtpJNI.CThostFtdcInstrumentTradingRightField_TradingRight_get(
				swigCPtr, this);
	}

	public CThostFtdcInstrumentTradingRightField() {
		this(CtpJNI.new_CThostFtdcInstrumentTradingRightField(), true);
	}

}
