/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcInvestorGroupField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcInvestorGroupField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcInvestorGroupField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcInvestorGroupField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcInvestorGroupField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcInvestorGroupField_BrokerID_get(swigCPtr, this);
	}

	public void setInvestorGroupID(String value) {
		CtpJNI.CThostFtdcInvestorGroupField_InvestorGroupID_set(swigCPtr, this,
				value);
	}

	public String getInvestorGroupID() {
		return CtpJNI.CThostFtdcInvestorGroupField_InvestorGroupID_get(
				swigCPtr, this);
	}

	public void setInvestorGroupName(String value) {
		CtpJNI.CThostFtdcInvestorGroupField_InvestorGroupName_set(swigCPtr,
				this, value);
	}

	public String getInvestorGroupName() {
		return CtpJNI.CThostFtdcInvestorGroupField_InvestorGroupName_get(
				swigCPtr, this);
	}

	public CThostFtdcInvestorGroupField() {
		this(CtpJNI.new_CThostFtdcInvestorGroupField(), true);
	}

}
