/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcLoginInfoField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcLoginInfoField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcLoginInfoField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcLoginInfoField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setFrontID(int value) {
		CtpJNI.CThostFtdcLoginInfoField_FrontID_set(swigCPtr, this, value);
	}

	public int getFrontID() {
		return CtpJNI.CThostFtdcLoginInfoField_FrontID_get(swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcLoginInfoField_SessionID_set(swigCPtr, this, value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcLoginInfoField_SessionID_get(swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcLoginInfoField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcLoginInfoField_BrokerID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcLoginInfoField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcLoginInfoField_UserID_get(swigCPtr, this);
	}

	public void setLoginDate(String value) {
		CtpJNI.CThostFtdcLoginInfoField_LoginDate_set(swigCPtr, this, value);
	}

	public String getLoginDate() {
		return CtpJNI.CThostFtdcLoginInfoField_LoginDate_get(swigCPtr, this);
	}

	public void setLoginTime(String value) {
		CtpJNI.CThostFtdcLoginInfoField_LoginTime_set(swigCPtr, this, value);
	}

	public String getLoginTime() {
		return CtpJNI.CThostFtdcLoginInfoField_LoginTime_get(swigCPtr, this);
	}

	public void setIPAddress(String value) {
		CtpJNI.CThostFtdcLoginInfoField_IPAddress_set(swigCPtr, this, value);
	}

	public String getIPAddress() {
		return CtpJNI.CThostFtdcLoginInfoField_IPAddress_get(swigCPtr, this);
	}

	public void setUserProductInfo(String value) {
		CtpJNI.CThostFtdcLoginInfoField_UserProductInfo_set(swigCPtr, this,
				value);
	}

	public String getUserProductInfo() {
		return CtpJNI.CThostFtdcLoginInfoField_UserProductInfo_get(swigCPtr,
				this);
	}

	public void setInterfaceProductInfo(String value) {
		CtpJNI.CThostFtdcLoginInfoField_InterfaceProductInfo_set(swigCPtr,
				this, value);
	}

	public String getInterfaceProductInfo() {
		return CtpJNI.CThostFtdcLoginInfoField_InterfaceProductInfo_get(
				swigCPtr, this);
	}

	public void setProtocolInfo(String value) {
		CtpJNI.CThostFtdcLoginInfoField_ProtocolInfo_set(swigCPtr, this, value);
	}

	public String getProtocolInfo() {
		return CtpJNI.CThostFtdcLoginInfoField_ProtocolInfo_get(swigCPtr, this);
	}

	public void setSystemName(String value) {
		CtpJNI.CThostFtdcLoginInfoField_SystemName_set(swigCPtr, this, value);
	}

	public String getSystemName() {
		return CtpJNI.CThostFtdcLoginInfoField_SystemName_get(swigCPtr, this);
	}

	public void setPassword(String value) {
		CtpJNI.CThostFtdcLoginInfoField_Password_set(swigCPtr, this, value);
	}

	public String getPassword() {
		return CtpJNI.CThostFtdcLoginInfoField_Password_get(swigCPtr, this);
	}

	public void setMaxOrderRef(String value) {
		CtpJNI.CThostFtdcLoginInfoField_MaxOrderRef_set(swigCPtr, this, value);
	}

	public String getMaxOrderRef() {
		return CtpJNI.CThostFtdcLoginInfoField_MaxOrderRef_get(swigCPtr, this);
	}

	public void setSHFETime(String value) {
		CtpJNI.CThostFtdcLoginInfoField_SHFETime_set(swigCPtr, this, value);
	}

	public String getSHFETime() {
		return CtpJNI.CThostFtdcLoginInfoField_SHFETime_get(swigCPtr, this);
	}

	public void setDCETime(String value) {
		CtpJNI.CThostFtdcLoginInfoField_DCETime_set(swigCPtr, this, value);
	}

	public String getDCETime() {
		return CtpJNI.CThostFtdcLoginInfoField_DCETime_get(swigCPtr, this);
	}

	public void setCZCETime(String value) {
		CtpJNI.CThostFtdcLoginInfoField_CZCETime_set(swigCPtr, this, value);
	}

	public String getCZCETime() {
		return CtpJNI.CThostFtdcLoginInfoField_CZCETime_get(swigCPtr, this);
	}

	public void setFFEXTime(String value) {
		CtpJNI.CThostFtdcLoginInfoField_FFEXTime_set(swigCPtr, this, value);
	}

	public String getFFEXTime() {
		return CtpJNI.CThostFtdcLoginInfoField_FFEXTime_get(swigCPtr, this);
	}

	public void setMacAddress(String value) {
		CtpJNI.CThostFtdcLoginInfoField_MacAddress_set(swigCPtr, this, value);
	}

	public String getMacAddress() {
		return CtpJNI.CThostFtdcLoginInfoField_MacAddress_get(swigCPtr, this);
	}

	public void setOneTimePassword(String value) {
		CtpJNI.CThostFtdcLoginInfoField_OneTimePassword_set(swigCPtr, this,
				value);
	}

	public String getOneTimePassword() {
		return CtpJNI.CThostFtdcLoginInfoField_OneTimePassword_get(swigCPtr,
				this);
	}

	public CThostFtdcLoginInfoField() {
		this(CtpJNI.new_CThostFtdcLoginInfoField(), true);
	}

}
