/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcNotifyFutureSignOutField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcNotifyFutureSignOutField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcNotifyFutureSignOutField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcNotifyFutureSignOutField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_TradeCode_set(swigCPtr, this,
				value);
	}

	public String getTradeCode() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_TradeCode_get(
				swigCPtr, this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_BankID_set(swigCPtr, this,
				value);
	}

	public String getBankID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_BankID_get(swigCPtr,
				this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_BankBranchID_set(swigCPtr,
				this, value);
	}

	public String getBankBranchID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_BankBranchID_get(
				swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_BrokerID_get(swigCPtr,
				this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_BrokerBranchID_set(swigCPtr,
				this, value);
	}

	public String getBrokerBranchID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_BrokerBranchID_get(
				swigCPtr, this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_TradeDate_set(swigCPtr, this,
				value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_TradeDate_get(
				swigCPtr, this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_TradeTime_set(swigCPtr, this,
				value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_TradeTime_get(
				swigCPtr, this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_BankSerial_set(swigCPtr,
				this, value);
	}

	public String getBankSerial() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_BankSerial_get(
				swigCPtr, this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_TradingDay_set(swigCPtr,
				this, value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_TradingDay_get(
				swigCPtr, this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_PlateSerial_set(swigCPtr,
				this, value);
	}

	public int getPlateSerial() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_PlateSerial_get(
				swigCPtr, this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_LastFragment_set(swigCPtr,
				this, value);
	}

	public char getLastFragment() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_LastFragment_get(
				swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_SessionID_set(swigCPtr, this,
				value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_SessionID_get(
				swigCPtr, this);
	}

	public void setInstallID(int value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_InstallID_set(swigCPtr, this,
				value);
	}

	public int getInstallID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_InstallID_get(
				swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_UserID_set(swigCPtr, this,
				value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_UserID_get(swigCPtr,
				this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_Digest_set(swigCPtr, this,
				value);
	}

	public String getDigest() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_Digest_get(swigCPtr,
				this);
	}

	public void setCurrencyID(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_CurrencyID_set(swigCPtr,
				this, value);
	}

	public String getCurrencyID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_CurrencyID_get(
				swigCPtr, this);
	}

	public void setDeviceID(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_DeviceID_set(swigCPtr, this,
				value);
	}

	public String getDeviceID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_DeviceID_get(swigCPtr,
				this);
	}

	public void setBrokerIDByBank(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_BrokerIDByBank_set(swigCPtr,
				this, value);
	}

	public String getBrokerIDByBank() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_BrokerIDByBank_get(
				swigCPtr, this);
	}

	public void setOperNo(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_OperNo_set(swigCPtr, this,
				value);
	}

	public String getOperNo() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_OperNo_get(swigCPtr,
				this);
	}

	public void setRequestID(int value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_RequestID_set(swigCPtr, this,
				value);
	}

	public int getRequestID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_RequestID_get(
				swigCPtr, this);
	}

	public void setTID(int value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_TID_set(swigCPtr, this, value);
	}

	public int getTID() {
		return CtpJNI
				.CThostFtdcNotifyFutureSignOutField_TID_get(swigCPtr, this);
	}

	public void setErrorID(int value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_ErrorID_set(swigCPtr, this,
				value);
	}

	public int getErrorID() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_ErrorID_get(swigCPtr,
				this);
	}

	public void setErrorMsg(String value) {
		CtpJNI.CThostFtdcNotifyFutureSignOutField_ErrorMsg_set(swigCPtr, this,
				value);
	}

	public String getErrorMsg() {
		return CtpJNI.CThostFtdcNotifyFutureSignOutField_ErrorMsg_get(swigCPtr,
				this);
	}

	public CThostFtdcNotifyFutureSignOutField() {
		this(CtpJNI.new_CThostFtdcNotifyFutureSignOutField(), true);
	}

}
