/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcInstrumentCommissionRateField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcInstrumentCommissionRateField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcInstrumentCommissionRateField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcInstrumentCommissionRateField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_InstrumentID_set(
				swigCPtr, this, value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcInstrumentCommissionRateField_InstrumentID_get(
				swigCPtr, this);
	}

	public void setInvestorRange(char value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_InvestorRange_set(
				swigCPtr, this, value);
	}

	public char getInvestorRange() {
		return CtpJNI
				.CThostFtdcInstrumentCommissionRateField_InvestorRange_get(
						swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_BrokerID_set(swigCPtr,
				this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcInstrumentCommissionRateField_BrokerID_get(
				swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_InvestorID_set(swigCPtr,
				this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcInstrumentCommissionRateField_InvestorID_get(
				swigCPtr, this);
	}

	public void setOpenRatioByMoney(double value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_OpenRatioByMoney_set(
				swigCPtr, this, value);
	}

	public double getOpenRatioByMoney() {
		return CtpJNI
				.CThostFtdcInstrumentCommissionRateField_OpenRatioByMoney_get(
						swigCPtr, this);
	}

	public void setOpenRatioByVolume(double value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_OpenRatioByVolume_set(
				swigCPtr, this, value);
	}

	public double getOpenRatioByVolume() {
		return CtpJNI
				.CThostFtdcInstrumentCommissionRateField_OpenRatioByVolume_get(
						swigCPtr, this);
	}

	public void setCloseRatioByMoney(double value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_CloseRatioByMoney_set(
				swigCPtr, this, value);
	}

	public double getCloseRatioByMoney() {
		return CtpJNI
				.CThostFtdcInstrumentCommissionRateField_CloseRatioByMoney_get(
						swigCPtr, this);
	}

	public void setCloseRatioByVolume(double value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_CloseRatioByVolume_set(
				swigCPtr, this, value);
	}

	public double getCloseRatioByVolume() {
		return CtpJNI
				.CThostFtdcInstrumentCommissionRateField_CloseRatioByVolume_get(
						swigCPtr, this);
	}

	public void setCloseTodayRatioByMoney(double value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_CloseTodayRatioByMoney_set(
				swigCPtr, this, value);
	}

	public double getCloseTodayRatioByMoney() {
		return CtpJNI
				.CThostFtdcInstrumentCommissionRateField_CloseTodayRatioByMoney_get(
						swigCPtr, this);
	}

	public void setCloseTodayRatioByVolume(double value) {
		CtpJNI.CThostFtdcInstrumentCommissionRateField_CloseTodayRatioByVolume_set(
				swigCPtr, this, value);
	}

	public double getCloseTodayRatioByVolume() {
		return CtpJNI
				.CThostFtdcInstrumentCommissionRateField_CloseTodayRatioByVolume_get(
						swigCPtr, this);
	}

	public CThostFtdcInstrumentCommissionRateField() {
		this(CtpJNI.new_CThostFtdcInstrumentCommissionRateField(), true);
	}

}
