/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQueryBrokerDepositField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQueryBrokerDepositField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQueryBrokerDepositField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQueryBrokerDepositField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcQueryBrokerDepositField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcQueryBrokerDepositField_BrokerID_get(swigCPtr,
				this);
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcQueryBrokerDepositField_ExchangeID_set(swigCPtr, this,
				value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcQueryBrokerDepositField_ExchangeID_get(
				swigCPtr, this);
	}

	public CThostFtdcQueryBrokerDepositField() {
		this(CtpJNI.new_CThostFtdcQueryBrokerDepositField(), true);
	}

}
