/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcSuperUserFunctionField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcSuperUserFunctionField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcSuperUserFunctionField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcSuperUserFunctionField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcSuperUserFunctionField_UserID_set(swigCPtr, this,
				value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcSuperUserFunctionField_UserID_get(swigCPtr,
				this);
	}

	public void setFunctionCode(char value) {
		CtpJNI.CThostFtdcSuperUserFunctionField_FunctionCode_set(swigCPtr,
				this, value);
	}

	public char getFunctionCode() {
		return CtpJNI.CThostFtdcSuperUserFunctionField_FunctionCode_get(
				swigCPtr, this);
	}

	public CThostFtdcSuperUserFunctionField() {
		this(CtpJNI.new_CThostFtdcSuperUserFunctionField(), true);
	}

}
