/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcInputOrderActionField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcInputOrderActionField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcInputOrderActionField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcInputOrderActionField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcInputOrderActionField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcInputOrderActionField_BrokerID_get(swigCPtr,
				this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcInputOrderActionField_InvestorID_set(swigCPtr, this,
				value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcInputOrderActionField_InvestorID_get(swigCPtr,
				this);
	}

	public void setOrderActionRef(int value) {
		CtpJNI.CThostFtdcInputOrderActionField_OrderActionRef_set(swigCPtr,
				this, value);
	}

	public int getOrderActionRef() {
		return CtpJNI.CThostFtdcInputOrderActionField_OrderActionRef_get(
				swigCPtr, this);
	}

	public void setOrderRef(String value) {
		CtpJNI.CThostFtdcInputOrderActionField_OrderRef_set(swigCPtr, this,
				value);
	}

	public String getOrderRef() {
		return CtpJNI.CThostFtdcInputOrderActionField_OrderRef_get(swigCPtr,
				this);
	}

	public void setRequestID(int value) {
		CtpJNI.CThostFtdcInputOrderActionField_RequestID_set(swigCPtr, this,
				value);
	}

	public int getRequestID() {
		return CtpJNI.CThostFtdcInputOrderActionField_RequestID_get(swigCPtr,
				this);
	}

	public void setFrontID(int value) {
		CtpJNI.CThostFtdcInputOrderActionField_FrontID_set(swigCPtr, this,
				value);
	}

	public int getFrontID() {
		return CtpJNI.CThostFtdcInputOrderActionField_FrontID_get(swigCPtr,
				this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcInputOrderActionField_SessionID_set(swigCPtr, this,
				value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcInputOrderActionField_SessionID_get(swigCPtr,
				this);
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcInputOrderActionField_ExchangeID_set(swigCPtr, this,
				value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcInputOrderActionField_ExchangeID_get(swigCPtr,
				this);
	}

	public void setOrderSysID(String value) {
		CtpJNI.CThostFtdcInputOrderActionField_OrderSysID_set(swigCPtr, this,
				value);
	}

	public String getOrderSysID() {
		return CtpJNI.CThostFtdcInputOrderActionField_OrderSysID_get(swigCPtr,
				this);
	}

	public void setActionFlag(char value) {
		CtpJNI.CThostFtdcInputOrderActionField_ActionFlag_set(swigCPtr, this,
				value);
	}

	public char getActionFlag() {
		return CtpJNI.CThostFtdcInputOrderActionField_ActionFlag_get(swigCPtr,
				this);
	}

	public void setLimitPrice(double value) {
		CtpJNI.CThostFtdcInputOrderActionField_LimitPrice_set(swigCPtr, this,
				value);
	}

	public double getLimitPrice() {
		return CtpJNI.CThostFtdcInputOrderActionField_LimitPrice_get(swigCPtr,
				this);
	}

	public void setVolumeChange(int value) {
		CtpJNI.CThostFtdcInputOrderActionField_VolumeChange_set(swigCPtr, this,
				value);
	}

	public int getVolumeChange() {
		return CtpJNI.CThostFtdcInputOrderActionField_VolumeChange_get(
				swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcInputOrderActionField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI
				.CThostFtdcInputOrderActionField_UserID_get(swigCPtr, this);
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcInputOrderActionField_InstrumentID_set(swigCPtr, this,
				value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcInputOrderActionField_InstrumentID_get(
				swigCPtr, this);
	}

	public CThostFtdcInputOrderActionField() {
		this(CtpJNI.new_CThostFtdcInputOrderActionField(), true);
	}

}
