/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcTransferFutureToBankRspField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcTransferFutureToBankRspField(long cPtr,
			boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcTransferFutureToBankRspField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcTransferFutureToBankRspField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setRetCode(String value) {
		CtpJNI.CThostFtdcTransferFutureToBankRspField_RetCode_set(swigCPtr,
				this, value);
	}

	public String getRetCode() {
		return CtpJNI.CThostFtdcTransferFutureToBankRspField_RetCode_get(
				swigCPtr, this);
	}

	public void setRetInfo(String value) {
		CtpJNI.CThostFtdcTransferFutureToBankRspField_RetInfo_set(swigCPtr,
				this, value);
	}

	public String getRetInfo() {
		return CtpJNI.CThostFtdcTransferFutureToBankRspField_RetInfo_get(
				swigCPtr, this);
	}

	public void setFutureAccount(String value) {
		CtpJNI.CThostFtdcTransferFutureToBankRspField_FutureAccount_set(
				swigCPtr, this, value);
	}

	public String getFutureAccount() {
		return CtpJNI.CThostFtdcTransferFutureToBankRspField_FutureAccount_get(
				swigCPtr, this);
	}

	public void setTradeAmt(double value) {
		CtpJNI.CThostFtdcTransferFutureToBankRspField_TradeAmt_set(swigCPtr,
				this, value);
	}

	public double getTradeAmt() {
		return CtpJNI.CThostFtdcTransferFutureToBankRspField_TradeAmt_get(
				swigCPtr, this);
	}

	public void setCustFee(double value) {
		CtpJNI.CThostFtdcTransferFutureToBankRspField_CustFee_set(swigCPtr,
				this, value);
	}

	public double getCustFee() {
		return CtpJNI.CThostFtdcTransferFutureToBankRspField_CustFee_get(
				swigCPtr, this);
	}

	public void setCurrencyCode(String value) {
		CtpJNI.CThostFtdcTransferFutureToBankRspField_CurrencyCode_set(
				swigCPtr, this, value);
	}

	public String getCurrencyCode() {
		return CtpJNI.CThostFtdcTransferFutureToBankRspField_CurrencyCode_get(
				swigCPtr, this);
	}

	public CThostFtdcTransferFutureToBankRspField() {
		this(CtpJNI.new_CThostFtdcTransferFutureToBankRspField(), true);
	}

}
