/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcOpenAccountField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcOpenAccountField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcOpenAccountField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcOpenAccountField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcOpenAccountField_TradeCode_set(swigCPtr, this, value);
	}

	public String getTradeCode() {
		return CtpJNI.CThostFtdcOpenAccountField_TradeCode_get(swigCPtr, this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BankID_set(swigCPtr, this, value);
	}

	public String getBankID() {
		return CtpJNI.CThostFtdcOpenAccountField_BankID_get(swigCPtr, this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BankBranchID_set(swigCPtr, this,
				value);
	}

	public String getBankBranchID() {
		return CtpJNI.CThostFtdcOpenAccountField_BankBranchID_get(swigCPtr,
				this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcOpenAccountField_BrokerID_get(swigCPtr, this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BrokerBranchID_set(swigCPtr, this,
				value);
	}

	public String getBrokerBranchID() {
		return CtpJNI.CThostFtdcOpenAccountField_BrokerBranchID_get(swigCPtr,
				this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcOpenAccountField_TradeDate_set(swigCPtr, this, value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcOpenAccountField_TradeDate_get(swigCPtr, this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcOpenAccountField_TradeTime_set(swigCPtr, this, value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcOpenAccountField_TradeTime_get(swigCPtr, this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BankSerial_set(swigCPtr, this, value);
	}

	public String getBankSerial() {
		return CtpJNI.CThostFtdcOpenAccountField_BankSerial_get(swigCPtr, this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcOpenAccountField_TradingDay_set(swigCPtr, this, value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcOpenAccountField_TradingDay_get(swigCPtr, this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcOpenAccountField_PlateSerial_set(swigCPtr, this, value);
	}

	public int getPlateSerial() {
		return CtpJNI
				.CThostFtdcOpenAccountField_PlateSerial_get(swigCPtr, this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcOpenAccountField_LastFragment_set(swigCPtr, this,
				value);
	}

	public char getLastFragment() {
		return CtpJNI.CThostFtdcOpenAccountField_LastFragment_get(swigCPtr,
				this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcOpenAccountField_SessionID_set(swigCPtr, this, value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcOpenAccountField_SessionID_get(swigCPtr, this);
	}

	public void setCustomerName(String value) {
		CtpJNI.CThostFtdcOpenAccountField_CustomerName_set(swigCPtr, this,
				value);
	}

	public String getCustomerName() {
		return CtpJNI.CThostFtdcOpenAccountField_CustomerName_get(swigCPtr,
				this);
	}

	public void setIdCardType(char value) {
		CtpJNI.CThostFtdcOpenAccountField_IdCardType_set(swigCPtr, this, value);
	}

	public char getIdCardType() {
		return CtpJNI.CThostFtdcOpenAccountField_IdCardType_get(swigCPtr, this);
	}

	public void setIdentifiedCardNo(String value) {
		CtpJNI.CThostFtdcOpenAccountField_IdentifiedCardNo_set(swigCPtr, this,
				value);
	}

	public String getIdentifiedCardNo() {
		return CtpJNI.CThostFtdcOpenAccountField_IdentifiedCardNo_get(swigCPtr,
				this);
	}

	public void setGender(char value) {
		CtpJNI.CThostFtdcOpenAccountField_Gender_set(swigCPtr, this, value);
	}

	public char getGender() {
		return CtpJNI.CThostFtdcOpenAccountField_Gender_get(swigCPtr, this);
	}

	public void setCountryCode(String value) {
		CtpJNI.CThostFtdcOpenAccountField_CountryCode_set(swigCPtr, this, value);
	}

	public String getCountryCode() {
		return CtpJNI
				.CThostFtdcOpenAccountField_CountryCode_get(swigCPtr, this);
	}

	public void setCustType(char value) {
		CtpJNI.CThostFtdcOpenAccountField_CustType_set(swigCPtr, this, value);
	}

	public char getCustType() {
		return CtpJNI.CThostFtdcOpenAccountField_CustType_get(swigCPtr, this);
	}

	public void setAddress(String value) {
		CtpJNI.CThostFtdcOpenAccountField_Address_set(swigCPtr, this, value);
	}

	public String getAddress() {
		return CtpJNI.CThostFtdcOpenAccountField_Address_get(swigCPtr, this);
	}

	public void setZipCode(String value) {
		CtpJNI.CThostFtdcOpenAccountField_ZipCode_set(swigCPtr, this, value);
	}

	public String getZipCode() {
		return CtpJNI.CThostFtdcOpenAccountField_ZipCode_get(swigCPtr, this);
	}

	public void setTelephone(String value) {
		CtpJNI.CThostFtdcOpenAccountField_Telephone_set(swigCPtr, this, value);
	}

	public String getTelephone() {
		return CtpJNI.CThostFtdcOpenAccountField_Telephone_get(swigCPtr, this);
	}

	public void setMobilePhone(String value) {
		CtpJNI.CThostFtdcOpenAccountField_MobilePhone_set(swigCPtr, this, value);
	}

	public String getMobilePhone() {
		return CtpJNI
				.CThostFtdcOpenAccountField_MobilePhone_get(swigCPtr, this);
	}

	public void setFax(String value) {
		CtpJNI.CThostFtdcOpenAccountField_Fax_set(swigCPtr, this, value);
	}

	public String getFax() {
		return CtpJNI.CThostFtdcOpenAccountField_Fax_get(swigCPtr, this);
	}

	public void setEMail(String value) {
		CtpJNI.CThostFtdcOpenAccountField_EMail_set(swigCPtr, this, value);
	}

	public String getEMail() {
		return CtpJNI.CThostFtdcOpenAccountField_EMail_get(swigCPtr, this);
	}

	public void setMoneyAccountStatus(char value) {
		CtpJNI.CThostFtdcOpenAccountField_MoneyAccountStatus_set(swigCPtr,
				this, value);
	}

	public char getMoneyAccountStatus() {
		return CtpJNI.CThostFtdcOpenAccountField_MoneyAccountStatus_get(
				swigCPtr, this);
	}

	public void setBankAccount(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BankAccount_set(swigCPtr, this, value);
	}

	public String getBankAccount() {
		return CtpJNI
				.CThostFtdcOpenAccountField_BankAccount_get(swigCPtr, this);
	}

	public void setBankPassWord(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BankPassWord_set(swigCPtr, this,
				value);
	}

	public String getBankPassWord() {
		return CtpJNI.CThostFtdcOpenAccountField_BankPassWord_get(swigCPtr,
				this);
	}

	public void setAccountID(String value) {
		CtpJNI.CThostFtdcOpenAccountField_AccountID_set(swigCPtr, this, value);
	}

	public String getAccountID() {
		return CtpJNI.CThostFtdcOpenAccountField_AccountID_get(swigCPtr, this);
	}

	public void setPassword(String value) {
		CtpJNI.CThostFtdcOpenAccountField_Password_set(swigCPtr, this, value);
	}

	public String getPassword() {
		return CtpJNI.CThostFtdcOpenAccountField_Password_get(swigCPtr, this);
	}

	public void setInstallID(int value) {
		CtpJNI.CThostFtdcOpenAccountField_InstallID_set(swigCPtr, this, value);
	}

	public int getInstallID() {
		return CtpJNI.CThostFtdcOpenAccountField_InstallID_get(swigCPtr, this);
	}

	public void setVerifyCertNoFlag(char value) {
		CtpJNI.CThostFtdcOpenAccountField_VerifyCertNoFlag_set(swigCPtr, this,
				value);
	}

	public char getVerifyCertNoFlag() {
		return CtpJNI.CThostFtdcOpenAccountField_VerifyCertNoFlag_get(swigCPtr,
				this);
	}

	public void setCurrencyID(String value) {
		CtpJNI.CThostFtdcOpenAccountField_CurrencyID_set(swigCPtr, this, value);
	}

	public String getCurrencyID() {
		return CtpJNI.CThostFtdcOpenAccountField_CurrencyID_get(swigCPtr, this);
	}

	public void setCashExchangeCode(char value) {
		CtpJNI.CThostFtdcOpenAccountField_CashExchangeCode_set(swigCPtr, this,
				value);
	}

	public char getCashExchangeCode() {
		return CtpJNI.CThostFtdcOpenAccountField_CashExchangeCode_get(swigCPtr,
				this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcOpenAccountField_Digest_set(swigCPtr, this, value);
	}

	public String getDigest() {
		return CtpJNI.CThostFtdcOpenAccountField_Digest_get(swigCPtr, this);
	}

	public void setBankAccType(char value) {
		CtpJNI.CThostFtdcOpenAccountField_BankAccType_set(swigCPtr, this, value);
	}

	public char getBankAccType() {
		return CtpJNI
				.CThostFtdcOpenAccountField_BankAccType_get(swigCPtr, this);
	}

	public void setDeviceID(String value) {
		CtpJNI.CThostFtdcOpenAccountField_DeviceID_set(swigCPtr, this, value);
	}

	public String getDeviceID() {
		return CtpJNI.CThostFtdcOpenAccountField_DeviceID_get(swigCPtr, this);
	}

	public void setBankSecuAccType(char value) {
		CtpJNI.CThostFtdcOpenAccountField_BankSecuAccType_set(swigCPtr, this,
				value);
	}

	public char getBankSecuAccType() {
		return CtpJNI.CThostFtdcOpenAccountField_BankSecuAccType_get(swigCPtr,
				this);
	}

	public void setBrokerIDByBank(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BrokerIDByBank_set(swigCPtr, this,
				value);
	}

	public String getBrokerIDByBank() {
		return CtpJNI.CThostFtdcOpenAccountField_BrokerIDByBank_get(swigCPtr,
				this);
	}

	public void setBankSecuAcc(String value) {
		CtpJNI.CThostFtdcOpenAccountField_BankSecuAcc_set(swigCPtr, this, value);
	}

	public String getBankSecuAcc() {
		return CtpJNI
				.CThostFtdcOpenAccountField_BankSecuAcc_get(swigCPtr, this);
	}

	public void setBankPwdFlag(char value) {
		CtpJNI.CThostFtdcOpenAccountField_BankPwdFlag_set(swigCPtr, this, value);
	}

	public char getBankPwdFlag() {
		return CtpJNI
				.CThostFtdcOpenAccountField_BankPwdFlag_get(swigCPtr, this);
	}

	public void setSecuPwdFlag(char value) {
		CtpJNI.CThostFtdcOpenAccountField_SecuPwdFlag_set(swigCPtr, this, value);
	}

	public char getSecuPwdFlag() {
		return CtpJNI
				.CThostFtdcOpenAccountField_SecuPwdFlag_get(swigCPtr, this);
	}

	public void setOperNo(String value) {
		CtpJNI.CThostFtdcOpenAccountField_OperNo_set(swigCPtr, this, value);
	}

	public String getOperNo() {
		return CtpJNI.CThostFtdcOpenAccountField_OperNo_get(swigCPtr, this);
	}

	public void setTID(int value) {
		CtpJNI.CThostFtdcOpenAccountField_TID_set(swigCPtr, this, value);
	}

	public int getTID() {
		return CtpJNI.CThostFtdcOpenAccountField_TID_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcOpenAccountField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcOpenAccountField_UserID_get(swigCPtr, this);
	}

	public void setErrorID(int value) {
		CtpJNI.CThostFtdcOpenAccountField_ErrorID_set(swigCPtr, this, value);
	}

	public int getErrorID() {
		return CtpJNI.CThostFtdcOpenAccountField_ErrorID_get(swigCPtr, this);
	}

	public void setErrorMsg(String value) {
		CtpJNI.CThostFtdcOpenAccountField_ErrorMsg_set(swigCPtr, this, value);
	}

	public String getErrorMsg() {
		return CtpJNI.CThostFtdcOpenAccountField_ErrorMsg_get(swigCPtr, this);
	}

	public CThostFtdcOpenAccountField() {
		this(CtpJNI.new_CThostFtdcOpenAccountField(), true);
	}

}
