/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcTradeField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcTradeField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcTradeField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcTradeField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcTradeField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcTradeField_BrokerID_get(swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcTradeField_InvestorID_set(swigCPtr, this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcTradeField_InvestorID_get(swigCPtr, this);
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcTradeField_InstrumentID_set(swigCPtr, this, value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcTradeField_InstrumentID_get(swigCPtr, this);
	}

	public void setOrderRef(String value) {
		CtpJNI.CThostFtdcTradeField_OrderRef_set(swigCPtr, this, value);
	}

	public String getOrderRef() {
		return CtpJNI.CThostFtdcTradeField_OrderRef_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcTradeField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcTradeField_UserID_get(swigCPtr, this);
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcTradeField_ExchangeID_set(swigCPtr, this, value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcTradeField_ExchangeID_get(swigCPtr, this);
	}

	public void setTradeID(String value) {
		CtpJNI.CThostFtdcTradeField_TradeID_set(swigCPtr, this, value);
	}

	public String getTradeID() {
		return CtpJNI.CThostFtdcTradeField_TradeID_get(swigCPtr, this);
	}

	public void setDirection(char value) {
		CtpJNI.CThostFtdcTradeField_Direction_set(swigCPtr, this, value);
	}

	public char getDirection() {
		return CtpJNI.CThostFtdcTradeField_Direction_get(swigCPtr, this);
	}

	public void setOrderSysID(String value) {
		CtpJNI.CThostFtdcTradeField_OrderSysID_set(swigCPtr, this, value);
	}

	public String getOrderSysID() {
		return CtpJNI.CThostFtdcTradeField_OrderSysID_get(swigCPtr, this);
	}

	public void setParticipantID(String value) {
		CtpJNI.CThostFtdcTradeField_ParticipantID_set(swigCPtr, this, value);
	}

	public String getParticipantID() {
		return CtpJNI.CThostFtdcTradeField_ParticipantID_get(swigCPtr, this);
	}

	public void setClientID(String value) {
		CtpJNI.CThostFtdcTradeField_ClientID_set(swigCPtr, this, value);
	}

	public String getClientID() {
		return CtpJNI.CThostFtdcTradeField_ClientID_get(swigCPtr, this);
	}

	public void setTradingRole(char value) {
		CtpJNI.CThostFtdcTradeField_TradingRole_set(swigCPtr, this, value);
	}

	public char getTradingRole() {
		return CtpJNI.CThostFtdcTradeField_TradingRole_get(swigCPtr, this);
	}

	public void setExchangeInstID(String value) {
		CtpJNI.CThostFtdcTradeField_ExchangeInstID_set(swigCPtr, this, value);
	}

	public String getExchangeInstID() {
		return CtpJNI.CThostFtdcTradeField_ExchangeInstID_get(swigCPtr, this);
	}

	public void setOffsetFlag(char value) {
		CtpJNI.CThostFtdcTradeField_OffsetFlag_set(swigCPtr, this, value);
	}

	public char getOffsetFlag() {
		return CtpJNI.CThostFtdcTradeField_OffsetFlag_get(swigCPtr, this);
	}

	public void setHedgeFlag(char value) {
		CtpJNI.CThostFtdcTradeField_HedgeFlag_set(swigCPtr, this, value);
	}

	public char getHedgeFlag() {
		return CtpJNI.CThostFtdcTradeField_HedgeFlag_get(swigCPtr, this);
	}

	public void setPrice(double value) {
		CtpJNI.CThostFtdcTradeField_Price_set(swigCPtr, this, value);
	}

	public double getPrice() {
		return CtpJNI.CThostFtdcTradeField_Price_get(swigCPtr, this);
	}

	public void setVolume(int value) {
		CtpJNI.CThostFtdcTradeField_Volume_set(swigCPtr, this, value);
	}

	public int getVolume() {
		return CtpJNI.CThostFtdcTradeField_Volume_get(swigCPtr, this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcTradeField_TradeDate_set(swigCPtr, this, value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcTradeField_TradeDate_get(swigCPtr, this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcTradeField_TradeTime_set(swigCPtr, this, value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcTradeField_TradeTime_get(swigCPtr, this);
	}

	public void setTradeType(char value) {
		CtpJNI.CThostFtdcTradeField_TradeType_set(swigCPtr, this, value);
	}

	public char getTradeType() {
		return CtpJNI.CThostFtdcTradeField_TradeType_get(swigCPtr, this);
	}

	public void setPriceSource(char value) {
		CtpJNI.CThostFtdcTradeField_PriceSource_set(swigCPtr, this, value);
	}

	public char getPriceSource() {
		return CtpJNI.CThostFtdcTradeField_PriceSource_get(swigCPtr, this);
	}

	public void setTraderID(String value) {
		CtpJNI.CThostFtdcTradeField_TraderID_set(swigCPtr, this, value);
	}

	public String getTraderID() {
		return CtpJNI.CThostFtdcTradeField_TraderID_get(swigCPtr, this);
	}

	public void setOrderLocalID(String value) {
		CtpJNI.CThostFtdcTradeField_OrderLocalID_set(swigCPtr, this, value);
	}

	public String getOrderLocalID() {
		return CtpJNI.CThostFtdcTradeField_OrderLocalID_get(swigCPtr, this);
	}

	public void setClearingPartID(String value) {
		CtpJNI.CThostFtdcTradeField_ClearingPartID_set(swigCPtr, this, value);
	}

	public String getClearingPartID() {
		return CtpJNI.CThostFtdcTradeField_ClearingPartID_get(swigCPtr, this);
	}

	public void setBusinessUnit(String value) {
		CtpJNI.CThostFtdcTradeField_BusinessUnit_set(swigCPtr, this, value);
	}

	public String getBusinessUnit() {
		return CtpJNI.CThostFtdcTradeField_BusinessUnit_get(swigCPtr, this);
	}

	public void setSequenceNo(int value) {
		CtpJNI.CThostFtdcTradeField_SequenceNo_set(swigCPtr, this, value);
	}

	public int getSequenceNo() {
		return CtpJNI.CThostFtdcTradeField_SequenceNo_get(swigCPtr, this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcTradeField_TradingDay_set(swigCPtr, this, value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcTradeField_TradingDay_get(swigCPtr, this);
	}

	public void setSettlementID(int value) {
		CtpJNI.CThostFtdcTradeField_SettlementID_set(swigCPtr, this, value);
	}

	public int getSettlementID() {
		return CtpJNI.CThostFtdcTradeField_SettlementID_get(swigCPtr, this);
	}

	public void setBrokerOrderSeq(int value) {
		CtpJNI.CThostFtdcTradeField_BrokerOrderSeq_set(swigCPtr, this, value);
	}

	public int getBrokerOrderSeq() {
		return CtpJNI.CThostFtdcTradeField_BrokerOrderSeq_get(swigCPtr, this);
	}

	public void setTradeSource(char value) {
		CtpJNI.CThostFtdcTradeField_TradeSource_set(swigCPtr, this, value);
	}

	public char getTradeSource() {
		return CtpJNI.CThostFtdcTradeField_TradeSource_get(swigCPtr, this);
	}

	public CThostFtdcTradeField() {
		this(CtpJNI.new_CThostFtdcTradeField(), true);
	}

}
