/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQryHisOrderField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQryHisOrderField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQryHisOrderField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQryHisOrderField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcQryHisOrderField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcQryHisOrderField_BrokerID_get(swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcQryHisOrderField_InvestorID_set(swigCPtr, this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcQryHisOrderField_InvestorID_get(swigCPtr, this);
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcQryHisOrderField_InstrumentID_set(swigCPtr, this,
				value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcQryHisOrderField_InstrumentID_get(swigCPtr,
				this);
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcQryHisOrderField_ExchangeID_set(swigCPtr, this, value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcQryHisOrderField_ExchangeID_get(swigCPtr, this);
	}

	public void setOrderSysID(String value) {
		CtpJNI.CThostFtdcQryHisOrderField_OrderSysID_set(swigCPtr, this, value);
	}

	public String getOrderSysID() {
		return CtpJNI.CThostFtdcQryHisOrderField_OrderSysID_get(swigCPtr, this);
	}

	public void setInsertTimeStart(String value) {
		CtpJNI.CThostFtdcQryHisOrderField_InsertTimeStart_set(swigCPtr, this,
				value);
	}

	public String getInsertTimeStart() {
		return CtpJNI.CThostFtdcQryHisOrderField_InsertTimeStart_get(swigCPtr,
				this);
	}

	public void setInsertTimeEnd(String value) {
		CtpJNI.CThostFtdcQryHisOrderField_InsertTimeEnd_set(swigCPtr, this,
				value);
	}

	public String getInsertTimeEnd() {
		return CtpJNI.CThostFtdcQryHisOrderField_InsertTimeEnd_get(swigCPtr,
				this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcQryHisOrderField_TradingDay_set(swigCPtr, this, value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcQryHisOrderField_TradingDay_get(swigCPtr, this);
	}

	public void setSettlementID(int value) {
		CtpJNI.CThostFtdcQryHisOrderField_SettlementID_set(swigCPtr, this,
				value);
	}

	public int getSettlementID() {
		return CtpJNI.CThostFtdcQryHisOrderField_SettlementID_get(swigCPtr,
				this);
	}

	public CThostFtdcQryHisOrderField() {
		this(CtpJNI.new_CThostFtdcQryHisOrderField(), true);
	}

}
