/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcOrderField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcOrderField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcOrderField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcOrderField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcOrderField_BrokerID_set(swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcOrderField_BrokerID_get(swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcOrderField_InvestorID_set(swigCPtr, this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcOrderField_InvestorID_get(swigCPtr, this);
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcOrderField_InstrumentID_set(swigCPtr, this, value);
	}

	public String getInstrumentID() {
		return CtpJNI.CThostFtdcOrderField_InstrumentID_get(swigCPtr, this);
	}

	public void setOrderRef(String value) {
		CtpJNI.CThostFtdcOrderField_OrderRef_set(swigCPtr, this, value);
	}

	public String getOrderRef() {
		return CtpJNI.CThostFtdcOrderField_OrderRef_get(swigCPtr, this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcOrderField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcOrderField_UserID_get(swigCPtr, this);
	}

	public void setOrderPriceType(char value) {
		CtpJNI.CThostFtdcOrderField_OrderPriceType_set(swigCPtr, this, value);
	}

	public char getOrderPriceType() {
		return CtpJNI.CThostFtdcOrderField_OrderPriceType_get(swigCPtr, this);
	}

	public void setDirection(char value) {
		CtpJNI.CThostFtdcOrderField_Direction_set(swigCPtr, this, value);
	}

	public char getDirection() {
		return CtpJNI.CThostFtdcOrderField_Direction_get(swigCPtr, this);
	}

	public void setCombOffsetFlag(String value) {
		CtpJNI.CThostFtdcOrderField_CombOffsetFlag_set(swigCPtr, this, value);
	}

	public String getCombOffsetFlag() {
		return CtpJNI.CThostFtdcOrderField_CombOffsetFlag_get(swigCPtr, this);
	}

	public void setCombHedgeFlag(String value) {
		CtpJNI.CThostFtdcOrderField_CombHedgeFlag_set(swigCPtr, this, value);
	}

	public String getCombHedgeFlag() {
		return CtpJNI.CThostFtdcOrderField_CombHedgeFlag_get(swigCPtr, this);
	}

	public void setLimitPrice(double value) {
		CtpJNI.CThostFtdcOrderField_LimitPrice_set(swigCPtr, this, value);
	}

	public double getLimitPrice() {
		return CtpJNI.CThostFtdcOrderField_LimitPrice_get(swigCPtr, this);
	}

	public void setVolumeTotalOriginal(int value) {
		CtpJNI.CThostFtdcOrderField_VolumeTotalOriginal_set(swigCPtr, this,
				value);
	}

	public int getVolumeTotalOriginal() {
		return CtpJNI.CThostFtdcOrderField_VolumeTotalOriginal_get(swigCPtr,
				this);
	}

	public void setTimeCondition(char value) {
		CtpJNI.CThostFtdcOrderField_TimeCondition_set(swigCPtr, this, value);
	}

	public char getTimeCondition() {
		return CtpJNI.CThostFtdcOrderField_TimeCondition_get(swigCPtr, this);
	}

	public void setGTDDate(String value) {
		CtpJNI.CThostFtdcOrderField_GTDDate_set(swigCPtr, this, value);
	}

	public String getGTDDate() {
		return CtpJNI.CThostFtdcOrderField_GTDDate_get(swigCPtr, this);
	}

	public void setVolumeCondition(char value) {
		CtpJNI.CThostFtdcOrderField_VolumeCondition_set(swigCPtr, this, value);
	}

	public char getVolumeCondition() {
		return CtpJNI.CThostFtdcOrderField_VolumeCondition_get(swigCPtr, this);
	}

	public void setMinVolume(int value) {
		CtpJNI.CThostFtdcOrderField_MinVolume_set(swigCPtr, this, value);
	}

	public int getMinVolume() {
		return CtpJNI.CThostFtdcOrderField_MinVolume_get(swigCPtr, this);
	}

	public void setContingentCondition(char value) {
		CtpJNI.CThostFtdcOrderField_ContingentCondition_set(swigCPtr, this,
				value);
	}

	public char getContingentCondition() {
		return CtpJNI.CThostFtdcOrderField_ContingentCondition_get(swigCPtr,
				this);
	}

	public void setStopPrice(double value) {
		CtpJNI.CThostFtdcOrderField_StopPrice_set(swigCPtr, this, value);
	}

	public double getStopPrice() {
		return CtpJNI.CThostFtdcOrderField_StopPrice_get(swigCPtr, this);
	}

	public void setForceCloseReason(char value) {
		CtpJNI.CThostFtdcOrderField_ForceCloseReason_set(swigCPtr, this, value);
	}

	public char getForceCloseReason() {
		return CtpJNI.CThostFtdcOrderField_ForceCloseReason_get(swigCPtr, this);
	}

	public void setIsAutoSuspend(int value) {
		CtpJNI.CThostFtdcOrderField_IsAutoSuspend_set(swigCPtr, this, value);
	}

	public int getIsAutoSuspend() {
		return CtpJNI.CThostFtdcOrderField_IsAutoSuspend_get(swigCPtr, this);
	}

	public void setBusinessUnit(String value) {
		CtpJNI.CThostFtdcOrderField_BusinessUnit_set(swigCPtr, this, value);
	}

	public String getBusinessUnit() {
		return CtpJNI.CThostFtdcOrderField_BusinessUnit_get(swigCPtr, this);
	}

	public void setRequestID(int value) {
		CtpJNI.CThostFtdcOrderField_RequestID_set(swigCPtr, this, value);
	}

	public int getRequestID() {
		return CtpJNI.CThostFtdcOrderField_RequestID_get(swigCPtr, this);
	}

	public void setOrderLocalID(String value) {
		CtpJNI.CThostFtdcOrderField_OrderLocalID_set(swigCPtr, this, value);
	}

	public String getOrderLocalID() {
		return CtpJNI.CThostFtdcOrderField_OrderLocalID_get(swigCPtr, this);
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcOrderField_ExchangeID_set(swigCPtr, this, value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcOrderField_ExchangeID_get(swigCPtr, this);
	}

	public void setParticipantID(String value) {
		CtpJNI.CThostFtdcOrderField_ParticipantID_set(swigCPtr, this, value);
	}

	public String getParticipantID() {
		return CtpJNI.CThostFtdcOrderField_ParticipantID_get(swigCPtr, this);
	}

	public void setClientID(String value) {
		CtpJNI.CThostFtdcOrderField_ClientID_set(swigCPtr, this, value);
	}

	public String getClientID() {
		return CtpJNI.CThostFtdcOrderField_ClientID_get(swigCPtr, this);
	}

	public void setExchangeInstID(String value) {
		CtpJNI.CThostFtdcOrderField_ExchangeInstID_set(swigCPtr, this, value);
	}

	public String getExchangeInstID() {
		return CtpJNI.CThostFtdcOrderField_ExchangeInstID_get(swigCPtr, this);
	}

	public void setTraderID(String value) {
		CtpJNI.CThostFtdcOrderField_TraderID_set(swigCPtr, this, value);
	}

	public String getTraderID() {
		return CtpJNI.CThostFtdcOrderField_TraderID_get(swigCPtr, this);
	}

	public void setInstallID(int value) {
		CtpJNI.CThostFtdcOrderField_InstallID_set(swigCPtr, this, value);
	}

	public int getInstallID() {
		return CtpJNI.CThostFtdcOrderField_InstallID_get(swigCPtr, this);
	}

	public void setOrderSubmitStatus(char value) {
		CtpJNI.CThostFtdcOrderField_OrderSubmitStatus_set(swigCPtr, this, value);
	}

	public char getOrderSubmitStatus() {
		return CtpJNI
				.CThostFtdcOrderField_OrderSubmitStatus_get(swigCPtr, this);
	}

	public void setNotifySequence(int value) {
		CtpJNI.CThostFtdcOrderField_NotifySequence_set(swigCPtr, this, value);
	}

	public int getNotifySequence() {
		return CtpJNI.CThostFtdcOrderField_NotifySequence_get(swigCPtr, this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcOrderField_TradingDay_set(swigCPtr, this, value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcOrderField_TradingDay_get(swigCPtr, this);
	}

	public void setSettlementID(int value) {
		CtpJNI.CThostFtdcOrderField_SettlementID_set(swigCPtr, this, value);
	}

	public int getSettlementID() {
		return CtpJNI.CThostFtdcOrderField_SettlementID_get(swigCPtr, this);
	}

	public void setOrderSysID(String value) {
		CtpJNI.CThostFtdcOrderField_OrderSysID_set(swigCPtr, this, value);
	}

	public String getOrderSysID() {
		return CtpJNI.CThostFtdcOrderField_OrderSysID_get(swigCPtr, this);
	}

	public void setOrderSource(char value) {
		CtpJNI.CThostFtdcOrderField_OrderSource_set(swigCPtr, this, value);
	}

	public char getOrderSource() {
		return CtpJNI.CThostFtdcOrderField_OrderSource_get(swigCPtr, this);
	}

	public void setOrderStatus(char value) {
		CtpJNI.CThostFtdcOrderField_OrderStatus_set(swigCPtr, this, value);
	}

	public char getOrderStatus() {
		return CtpJNI.CThostFtdcOrderField_OrderStatus_get(swigCPtr, this);
	}

	public void setOrderType(char value) {
		CtpJNI.CThostFtdcOrderField_OrderType_set(swigCPtr, this, value);
	}

	public char getOrderType() {
		return CtpJNI.CThostFtdcOrderField_OrderType_get(swigCPtr, this);
	}

	public void setVolumeTraded(int value) {
		CtpJNI.CThostFtdcOrderField_VolumeTraded_set(swigCPtr, this, value);
	}

	public int getVolumeTraded() {
		return CtpJNI.CThostFtdcOrderField_VolumeTraded_get(swigCPtr, this);
	}

	public void setVolumeTotal(int value) {
		CtpJNI.CThostFtdcOrderField_VolumeTotal_set(swigCPtr, this, value);
	}

	public int getVolumeTotal() {
		return CtpJNI.CThostFtdcOrderField_VolumeTotal_get(swigCPtr, this);
	}

	public void setInsertDate(String value) {
		CtpJNI.CThostFtdcOrderField_InsertDate_set(swigCPtr, this, value);
	}

	public String getInsertDate() {
		return CtpJNI.CThostFtdcOrderField_InsertDate_get(swigCPtr, this);
	}

	public void setInsertTime(String value) {
		CtpJNI.CThostFtdcOrderField_InsertTime_set(swigCPtr, this, value);
	}

	public String getInsertTime() {
		return CtpJNI.CThostFtdcOrderField_InsertTime_get(swigCPtr, this);
	}

	public void setActiveTime(String value) {
		CtpJNI.CThostFtdcOrderField_ActiveTime_set(swigCPtr, this, value);
	}

	public String getActiveTime() {
		return CtpJNI.CThostFtdcOrderField_ActiveTime_get(swigCPtr, this);
	}

	public void setSuspendTime(String value) {
		CtpJNI.CThostFtdcOrderField_SuspendTime_set(swigCPtr, this, value);
	}

	public String getSuspendTime() {
		return CtpJNI.CThostFtdcOrderField_SuspendTime_get(swigCPtr, this);
	}

	public void setUpdateTime(String value) {
		CtpJNI.CThostFtdcOrderField_UpdateTime_set(swigCPtr, this, value);
	}

	public String getUpdateTime() {
		return CtpJNI.CThostFtdcOrderField_UpdateTime_get(swigCPtr, this);
	}

	public void setCancelTime(String value) {
		CtpJNI.CThostFtdcOrderField_CancelTime_set(swigCPtr, this, value);
	}

	public String getCancelTime() {
		return CtpJNI.CThostFtdcOrderField_CancelTime_get(swigCPtr, this);
	}

	public void setActiveTraderID(String value) {
		CtpJNI.CThostFtdcOrderField_ActiveTraderID_set(swigCPtr, this, value);
	}

	public String getActiveTraderID() {
		return CtpJNI.CThostFtdcOrderField_ActiveTraderID_get(swigCPtr, this);
	}

	public void setClearingPartID(String value) {
		CtpJNI.CThostFtdcOrderField_ClearingPartID_set(swigCPtr, this, value);
	}

	public String getClearingPartID() {
		return CtpJNI.CThostFtdcOrderField_ClearingPartID_get(swigCPtr, this);
	}

	public void setSequenceNo(int value) {
		CtpJNI.CThostFtdcOrderField_SequenceNo_set(swigCPtr, this, value);
	}

	public int getSequenceNo() {
		return CtpJNI.CThostFtdcOrderField_SequenceNo_get(swigCPtr, this);
	}

	public void setFrontID(int value) {
		CtpJNI.CThostFtdcOrderField_FrontID_set(swigCPtr, this, value);
	}

	public int getFrontID() {
		return CtpJNI.CThostFtdcOrderField_FrontID_get(swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcOrderField_SessionID_set(swigCPtr, this, value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcOrderField_SessionID_get(swigCPtr, this);
	}

	public void setUserProductInfo(String value) {
		CtpJNI.CThostFtdcOrderField_UserProductInfo_set(swigCPtr, this, value);
	}

	public String getUserProductInfo() {
		return CtpJNI.CThostFtdcOrderField_UserProductInfo_get(swigCPtr, this);
	}

	public void setStatusMsg(String value) {
		CtpJNI.CThostFtdcOrderField_StatusMsg_set(swigCPtr, this, value);
	}

	public String getStatusMsg() {
		return CtpJNI.CThostFtdcOrderField_StatusMsg_get(swigCPtr, this);
	}

	public void setUserForceClose(int value) {
		CtpJNI.CThostFtdcOrderField_UserForceClose_set(swigCPtr, this, value);
	}

	public int getUserForceClose() {
		return CtpJNI.CThostFtdcOrderField_UserForceClose_get(swigCPtr, this);
	}

	public void setActiveUserID(String value) {
		CtpJNI.CThostFtdcOrderField_ActiveUserID_set(swigCPtr, this, value);
	}

	public String getActiveUserID() {
		return CtpJNI.CThostFtdcOrderField_ActiveUserID_get(swigCPtr, this);
	}

	public void setBrokerOrderSeq(int value) {
		CtpJNI.CThostFtdcOrderField_BrokerOrderSeq_set(swigCPtr, this, value);
	}

	public int getBrokerOrderSeq() {
		return CtpJNI.CThostFtdcOrderField_BrokerOrderSeq_get(swigCPtr, this);
	}

	public void setRelativeOrderSysID(String value) {
		CtpJNI.CThostFtdcOrderField_RelativeOrderSysID_set(swigCPtr, this,
				value);
	}

	public String getRelativeOrderSysID() {
		return CtpJNI.CThostFtdcOrderField_RelativeOrderSysID_get(swigCPtr,
				this);
	}

	public void setZCETotalTradedVolume(int value) {
		CtpJNI.CThostFtdcOrderField_ZCETotalTradedVolume_set(swigCPtr, this,
				value);
	}

	public int getZCETotalTradedVolume() {
		return CtpJNI.CThostFtdcOrderField_ZCETotalTradedVolume_get(swigCPtr,
				this);
	}

	public void setIsSwapOrder(int value) {
		CtpJNI.CThostFtdcOrderField_IsSwapOrder_set(swigCPtr, this, value);
	}

	public int getIsSwapOrder() {
		return CtpJNI.CThostFtdcOrderField_IsSwapOrder_get(swigCPtr, this);
	}

	public CThostFtdcOrderField() {
		this(CtpJNI.new_CThostFtdcOrderField(), true);
	}

}
