/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcVerifyCustInfoField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcVerifyCustInfoField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcVerifyCustInfoField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcVerifyCustInfoField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setCustomerName(String value) {
		CtpJNI.CThostFtdcVerifyCustInfoField_CustomerName_set(swigCPtr, this,
				value);
	}

	public String getCustomerName() {
		return CtpJNI.CThostFtdcVerifyCustInfoField_CustomerName_get(swigCPtr,
				this);
	}

	public void setIdCardType(char value) {
		CtpJNI.CThostFtdcVerifyCustInfoField_IdCardType_set(swigCPtr, this,
				value);
	}

	public char getIdCardType() {
		return CtpJNI.CThostFtdcVerifyCustInfoField_IdCardType_get(swigCPtr,
				this);
	}

	public void setIdentifiedCardNo(String value) {
		CtpJNI.CThostFtdcVerifyCustInfoField_IdentifiedCardNo_set(swigCPtr,
				this, value);
	}

	public String getIdentifiedCardNo() {
		return CtpJNI.CThostFtdcVerifyCustInfoField_IdentifiedCardNo_get(
				swigCPtr, this);
	}

	public void setCustType(char value) {
		CtpJNI.CThostFtdcVerifyCustInfoField_CustType_set(swigCPtr, this, value);
	}

	public char getCustType() {
		return CtpJNI
				.CThostFtdcVerifyCustInfoField_CustType_get(swigCPtr, this);
	}

	public CThostFtdcVerifyCustInfoField() {
		this(CtpJNI.new_CThostFtdcVerifyCustInfoField(), true);
	}

}
