/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcQryBrokerTradingParamsField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcQryBrokerTradingParamsField(long cPtr,
			boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcQryBrokerTradingParamsField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcQryBrokerTradingParamsField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcQryBrokerTradingParamsField_BrokerID_set(swigCPtr,
				this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcQryBrokerTradingParamsField_BrokerID_get(
				swigCPtr, this);
	}

	public void setInvestorID(String value) {
		CtpJNI.CThostFtdcQryBrokerTradingParamsField_InvestorID_set(swigCPtr,
				this, value);
	}

	public String getInvestorID() {
		return CtpJNI.CThostFtdcQryBrokerTradingParamsField_InvestorID_get(
				swigCPtr, this);
	}

	public CThostFtdcQryBrokerTradingParamsField() {
		this(CtpJNI.new_CThostFtdcQryBrokerTradingParamsField(), true);
	}

}
