/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcRspFutureSignInField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcRspFutureSignInField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcRspFutureSignInField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcRspFutureSignInField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_TradeCode_set(swigCPtr, this,
				value);
	}

	public String getTradeCode() {
		return CtpJNI.CThostFtdcRspFutureSignInField_TradeCode_get(swigCPtr,
				this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_BankID_set(swigCPtr, this, value);
	}

	public String getBankID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_BankID_get(swigCPtr, this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_BankBranchID_set(swigCPtr, this,
				value);
	}

	public String getBankBranchID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_BankBranchID_get(swigCPtr,
				this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_BrokerID_set(swigCPtr, this,
				value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_BrokerID_get(swigCPtr,
				this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_BrokerBranchID_set(swigCPtr,
				this, value);
	}

	public String getBrokerBranchID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_BrokerBranchID_get(
				swigCPtr, this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_TradeDate_set(swigCPtr, this,
				value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcRspFutureSignInField_TradeDate_get(swigCPtr,
				this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_TradeTime_set(swigCPtr, this,
				value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcRspFutureSignInField_TradeTime_get(swigCPtr,
				this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_BankSerial_set(swigCPtr, this,
				value);
	}

	public String getBankSerial() {
		return CtpJNI.CThostFtdcRspFutureSignInField_BankSerial_get(swigCPtr,
				this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_TradingDay_set(swigCPtr, this,
				value);
	}

	public String getTradingDay() {
		return CtpJNI.CThostFtdcRspFutureSignInField_TradingDay_get(swigCPtr,
				this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcRspFutureSignInField_PlateSerial_set(swigCPtr, this,
				value);
	}

	public int getPlateSerial() {
		return CtpJNI.CThostFtdcRspFutureSignInField_PlateSerial_get(swigCPtr,
				this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcRspFutureSignInField_LastFragment_set(swigCPtr, this,
				value);
	}

	public char getLastFragment() {
		return CtpJNI.CThostFtdcRspFutureSignInField_LastFragment_get(swigCPtr,
				this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcRspFutureSignInField_SessionID_set(swigCPtr, this,
				value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_SessionID_get(swigCPtr,
				this);
	}

	public void setInstallID(int value) {
		CtpJNI.CThostFtdcRspFutureSignInField_InstallID_set(swigCPtr, this,
				value);
	}

	public int getInstallID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_InstallID_get(swigCPtr,
				this);
	}

	public void setUserID(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_UserID_set(swigCPtr, this, value);
	}

	public String getUserID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_UserID_get(swigCPtr, this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_Digest_set(swigCPtr, this, value);
	}

	public String getDigest() {
		return CtpJNI.CThostFtdcRspFutureSignInField_Digest_get(swigCPtr, this);
	}

	public void setCurrencyID(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_CurrencyID_set(swigCPtr, this,
				value);
	}

	public String getCurrencyID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_CurrencyID_get(swigCPtr,
				this);
	}

	public void setDeviceID(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_DeviceID_set(swigCPtr, this,
				value);
	}

	public String getDeviceID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_DeviceID_get(swigCPtr,
				this);
	}

	public void setBrokerIDByBank(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_BrokerIDByBank_set(swigCPtr,
				this, value);
	}

	public String getBrokerIDByBank() {
		return CtpJNI.CThostFtdcRspFutureSignInField_BrokerIDByBank_get(
				swigCPtr, this);
	}

	public void setOperNo(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_OperNo_set(swigCPtr, this, value);
	}

	public String getOperNo() {
		return CtpJNI.CThostFtdcRspFutureSignInField_OperNo_get(swigCPtr, this);
	}

	public void setRequestID(int value) {
		CtpJNI.CThostFtdcRspFutureSignInField_RequestID_set(swigCPtr, this,
				value);
	}

	public int getRequestID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_RequestID_get(swigCPtr,
				this);
	}

	public void setTID(int value) {
		CtpJNI.CThostFtdcRspFutureSignInField_TID_set(swigCPtr, this, value);
	}

	public int getTID() {
		return CtpJNI.CThostFtdcRspFutureSignInField_TID_get(swigCPtr, this);
	}

	public void setErrorID(int value) {
		CtpJNI.CThostFtdcRspFutureSignInField_ErrorID_set(swigCPtr, this, value);
	}

	public int getErrorID() {
		return CtpJNI
				.CThostFtdcRspFutureSignInField_ErrorID_get(swigCPtr, this);
	}

	public void setErrorMsg(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_ErrorMsg_set(swigCPtr, this,
				value);
	}

	public String getErrorMsg() {
		return CtpJNI.CThostFtdcRspFutureSignInField_ErrorMsg_get(swigCPtr,
				this);
	}

	public void setPinKey(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_PinKey_set(swigCPtr, this, value);
	}

	public String getPinKey() {
		return CtpJNI.CThostFtdcRspFutureSignInField_PinKey_get(swigCPtr, this);
	}

	public void setMacKey(String value) {
		CtpJNI.CThostFtdcRspFutureSignInField_MacKey_set(swigCPtr, this, value);
	}

	public String getMacKey() {
		return CtpJNI.CThostFtdcRspFutureSignInField_MacKey_get(swigCPtr, this);
	}

	public CThostFtdcRspFutureSignInField() {
		this(CtpJNI.new_CThostFtdcRspFutureSignInField(), true);
	}

}
