/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcInstrumentField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CThostFtdcInstrumentField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcInstrumentField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcInstrumentField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setInstrumentID(String value) {
		CtpJNI.CThostFtdcInstrumentField_InstrumentID_set(swigCPtr, this, value);
	}

	public String getInstrumentID() {
		return CtpJNI
				.CThostFtdcInstrumentField_InstrumentID_get(swigCPtr, this);
	}

	public void setExchangeID(String value) {
		CtpJNI.CThostFtdcInstrumentField_ExchangeID_set(swigCPtr, this, value);
	}

	public String getExchangeID() {
		return CtpJNI.CThostFtdcInstrumentField_ExchangeID_get(swigCPtr, this);
	}

	public void setInstrumentName(String value) {
		CtpJNI.CThostFtdcInstrumentField_InstrumentName_set(swigCPtr, this,
				value);
	}

	public String getInstrumentName() {
		return CtpJNI.CThostFtdcInstrumentField_InstrumentName_get(swigCPtr,
				this);
	}

	public void setExchangeInstID(String value) {
		CtpJNI.CThostFtdcInstrumentField_ExchangeInstID_set(swigCPtr, this,
				value);
	}

	public String getExchangeInstID() {
		return CtpJNI.CThostFtdcInstrumentField_ExchangeInstID_get(swigCPtr,
				this);
	}

	public void setProductID(String value) {
		CtpJNI.CThostFtdcInstrumentField_ProductID_set(swigCPtr, this, value);
	}

	public String getProductID() {
		return CtpJNI.CThostFtdcInstrumentField_ProductID_get(swigCPtr, this);
	}

	public void setProductClass(char value) {
		CtpJNI.CThostFtdcInstrumentField_ProductClass_set(swigCPtr, this, value);
	}

	public char getProductClass() {
		return CtpJNI
				.CThostFtdcInstrumentField_ProductClass_get(swigCPtr, this);
	}

	public void setDeliveryYear(int value) {
		CtpJNI.CThostFtdcInstrumentField_DeliveryYear_set(swigCPtr, this, value);
	}

	public int getDeliveryYear() {
		return CtpJNI
				.CThostFtdcInstrumentField_DeliveryYear_get(swigCPtr, this);
	}

	public void setDeliveryMonth(int value) {
		CtpJNI.CThostFtdcInstrumentField_DeliveryMonth_set(swigCPtr, this,
				value);
	}

	public int getDeliveryMonth() {
		return CtpJNI.CThostFtdcInstrumentField_DeliveryMonth_get(swigCPtr,
				this);
	}

	public void setMaxMarketOrderVolume(int value) {
		CtpJNI.CThostFtdcInstrumentField_MaxMarketOrderVolume_set(swigCPtr,
				this, value);
	}

	public int getMaxMarketOrderVolume() {
		return CtpJNI.CThostFtdcInstrumentField_MaxMarketOrderVolume_get(
				swigCPtr, this);
	}

	public void setMinMarketOrderVolume(int value) {
		CtpJNI.CThostFtdcInstrumentField_MinMarketOrderVolume_set(swigCPtr,
				this, value);
	}

	public int getMinMarketOrderVolume() {
		return CtpJNI.CThostFtdcInstrumentField_MinMarketOrderVolume_get(
				swigCPtr, this);
	}

	public void setMaxLimitOrderVolume(int value) {
		CtpJNI.CThostFtdcInstrumentField_MaxLimitOrderVolume_set(swigCPtr,
				this, value);
	}

	public int getMaxLimitOrderVolume() {
		return CtpJNI.CThostFtdcInstrumentField_MaxLimitOrderVolume_get(
				swigCPtr, this);
	}

	public void setMinLimitOrderVolume(int value) {
		CtpJNI.CThostFtdcInstrumentField_MinLimitOrderVolume_set(swigCPtr,
				this, value);
	}

	public int getMinLimitOrderVolume() {
		return CtpJNI.CThostFtdcInstrumentField_MinLimitOrderVolume_get(
				swigCPtr, this);
	}

	public void setVolumeMultiple(int value) {
		CtpJNI.CThostFtdcInstrumentField_VolumeMultiple_set(swigCPtr, this,
				value);
	}

	public int getVolumeMultiple() {
		return CtpJNI.CThostFtdcInstrumentField_VolumeMultiple_get(swigCPtr,
				this);
	}

	public void setPriceTick(double value) {
		CtpJNI.CThostFtdcInstrumentField_PriceTick_set(swigCPtr, this, value);
	}

	public double getPriceTick() {
		return CtpJNI.CThostFtdcInstrumentField_PriceTick_get(swigCPtr, this);
	}

	public void setCreateDate(String value) {
		CtpJNI.CThostFtdcInstrumentField_CreateDate_set(swigCPtr, this, value);
	}

	public String getCreateDate() {
		return CtpJNI.CThostFtdcInstrumentField_CreateDate_get(swigCPtr, this);
	}

	public void setOpenDate(String value) {
		CtpJNI.CThostFtdcInstrumentField_OpenDate_set(swigCPtr, this, value);
	}

	public String getOpenDate() {
		return CtpJNI.CThostFtdcInstrumentField_OpenDate_get(swigCPtr, this);
	}

	public void setExpireDate(String value) {
		CtpJNI.CThostFtdcInstrumentField_ExpireDate_set(swigCPtr, this, value);
	}

	public String getExpireDate() {
		return CtpJNI.CThostFtdcInstrumentField_ExpireDate_get(swigCPtr, this);
	}

	public void setStartDelivDate(String value) {
		CtpJNI.CThostFtdcInstrumentField_StartDelivDate_set(swigCPtr, this,
				value);
	}

	public String getStartDelivDate() {
		return CtpJNI.CThostFtdcInstrumentField_StartDelivDate_get(swigCPtr,
				this);
	}

	public void setEndDelivDate(String value) {
		CtpJNI.CThostFtdcInstrumentField_EndDelivDate_set(swigCPtr, this, value);
	}

	public String getEndDelivDate() {
		return CtpJNI
				.CThostFtdcInstrumentField_EndDelivDate_get(swigCPtr, this);
	}

	public void setInstLifePhase(char value) {
		CtpJNI.CThostFtdcInstrumentField_InstLifePhase_set(swigCPtr, this,
				value);
	}

	public char getInstLifePhase() {
		return CtpJNI.CThostFtdcInstrumentField_InstLifePhase_get(swigCPtr,
				this);
	}

	public void setIsTrading(int value) {
		CtpJNI.CThostFtdcInstrumentField_IsTrading_set(swigCPtr, this, value);
	}

	public int getIsTrading() {
		return CtpJNI.CThostFtdcInstrumentField_IsTrading_get(swigCPtr, this);
	}

	public void setPositionType(char value) {
		CtpJNI.CThostFtdcInstrumentField_PositionType_set(swigCPtr, this, value);
	}

	public char getPositionType() {
		return CtpJNI
				.CThostFtdcInstrumentField_PositionType_get(swigCPtr, this);
	}

	public void setPositionDateType(char value) {
		CtpJNI.CThostFtdcInstrumentField_PositionDateType_set(swigCPtr, this,
				value);
	}

	public char getPositionDateType() {
		return CtpJNI.CThostFtdcInstrumentField_PositionDateType_get(swigCPtr,
				this);
	}

	public void setLongMarginRatio(double value) {
		CtpJNI.CThostFtdcInstrumentField_LongMarginRatio_set(swigCPtr, this,
				value);
	}

	public double getLongMarginRatio() {
		return CtpJNI.CThostFtdcInstrumentField_LongMarginRatio_get(swigCPtr,
				this);
	}

	public void setShortMarginRatio(double value) {
		CtpJNI.CThostFtdcInstrumentField_ShortMarginRatio_set(swigCPtr, this,
				value);
	}

	public double getShortMarginRatio() {
		return CtpJNI.CThostFtdcInstrumentField_ShortMarginRatio_get(swigCPtr,
				this);
	}

	public void setMaxMarginSideAlgorithm(char value) {
		CtpJNI.CThostFtdcInstrumentField_MaxMarginSideAlgorithm_set(swigCPtr,
				this, value);
	}

	public char getMaxMarginSideAlgorithm() {
		return CtpJNI.CThostFtdcInstrumentField_MaxMarginSideAlgorithm_get(
				swigCPtr, this);
	}

	public CThostFtdcInstrumentField() {
		this(CtpJNI.new_CThostFtdcInstrumentField(), true);
	}

}
