/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp.field;

import com.ctp.CtpJNI;

public class CThostFtdcRspQueryTradeResultBySerialField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CThostFtdcRspQueryTradeResultBySerialField(long cPtr,
			boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CThostFtdcRspQueryTradeResultBySerialField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CtpJNI.delete_CThostFtdcRspQueryTradeResultBySerialField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTradeCode(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_TradeCode_set(
				swigCPtr, this, value);
	}

	public String getTradeCode() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_TradeCode_get(
				swigCPtr, this);
	}

	public void setBankID(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BankID_set(swigCPtr,
				this, value);
	}

	public String getBankID() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BankID_get(
				swigCPtr, this);
	}

	public void setBankBranchID(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BankBranchID_set(
				swigCPtr, this, value);
	}

	public String getBankBranchID() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_BankBranchID_get(
						swigCPtr, this);
	}

	public void setBrokerID(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BrokerID_set(
				swigCPtr, this, value);
	}

	public String getBrokerID() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BrokerID_get(
				swigCPtr, this);
	}

	public void setBrokerBranchID(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BrokerBranchID_set(
				swigCPtr, this, value);
	}

	public String getBrokerBranchID() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_BrokerBranchID_get(
						swigCPtr, this);
	}

	public void setTradeDate(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_TradeDate_set(
				swigCPtr, this, value);
	}

	public String getTradeDate() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_TradeDate_get(
				swigCPtr, this);
	}

	public void setTradeTime(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_TradeTime_set(
				swigCPtr, this, value);
	}

	public String getTradeTime() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_TradeTime_get(
				swigCPtr, this);
	}

	public void setBankSerial(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BankSerial_set(
				swigCPtr, this, value);
	}

	public String getBankSerial() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_BankSerial_get(
						swigCPtr, this);
	}

	public void setTradingDay(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_TradingDay_set(
				swigCPtr, this, value);
	}

	public String getTradingDay() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_TradingDay_get(
						swigCPtr, this);
	}

	public void setPlateSerial(int value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_PlateSerial_set(
				swigCPtr, this, value);
	}

	public int getPlateSerial() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_PlateSerial_get(
						swigCPtr, this);
	}

	public void setLastFragment(char value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_LastFragment_set(
				swigCPtr, this, value);
	}

	public char getLastFragment() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_LastFragment_get(
						swigCPtr, this);
	}

	public void setSessionID(int value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_SessionID_set(
				swigCPtr, this, value);
	}

	public int getSessionID() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_SessionID_get(
				swigCPtr, this);
	}

	public void setErrorID(int value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_ErrorID_set(swigCPtr,
				this, value);
	}

	public int getErrorID() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_ErrorID_get(
				swigCPtr, this);
	}

	public void setErrorMsg(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_ErrorMsg_set(
				swigCPtr, this, value);
	}

	public String getErrorMsg() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_ErrorMsg_get(
				swigCPtr, this);
	}

	public void setReference(int value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_Reference_set(
				swigCPtr, this, value);
	}

	public int getReference() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_Reference_get(
				swigCPtr, this);
	}

	public void setRefrenceIssureType(char value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_RefrenceIssureType_set(
				swigCPtr, this, value);
	}

	public char getRefrenceIssureType() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_RefrenceIssureType_get(
						swigCPtr, this);
	}

	public void setRefrenceIssure(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_RefrenceIssure_set(
				swigCPtr, this, value);
	}

	public String getRefrenceIssure() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_RefrenceIssure_get(
						swigCPtr, this);
	}

	public void setOriginReturnCode(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_OriginReturnCode_set(
				swigCPtr, this, value);
	}

	public String getOriginReturnCode() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_OriginReturnCode_get(
						swigCPtr, this);
	}

	public void setOriginDescrInfoForReturnCode(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_OriginDescrInfoForReturnCode_set(
				swigCPtr, this, value);
	}

	public String getOriginDescrInfoForReturnCode() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_OriginDescrInfoForReturnCode_get(
						swigCPtr, this);
	}

	public void setBankAccount(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BankAccount_set(
				swigCPtr, this, value);
	}

	public String getBankAccount() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_BankAccount_get(
						swigCPtr, this);
	}

	public void setBankPassWord(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_BankPassWord_set(
				swigCPtr, this, value);
	}

	public String getBankPassWord() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_BankPassWord_get(
						swigCPtr, this);
	}

	public void setAccountID(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_AccountID_set(
				swigCPtr, this, value);
	}

	public String getAccountID() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_AccountID_get(
				swigCPtr, this);
	}

	public void setPassword(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_Password_set(
				swigCPtr, this, value);
	}

	public String getPassword() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_Password_get(
				swigCPtr, this);
	}

	public void setCurrencyID(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_CurrencyID_set(
				swigCPtr, this, value);
	}

	public String getCurrencyID() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_CurrencyID_get(
						swigCPtr, this);
	}

	public void setTradeAmount(double value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_TradeAmount_set(
				swigCPtr, this, value);
	}

	public double getTradeAmount() {
		return CtpJNI
				.CThostFtdcRspQueryTradeResultBySerialField_TradeAmount_get(
						swigCPtr, this);
	}

	public void setDigest(String value) {
		CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_Digest_set(swigCPtr,
				this, value);
	}

	public String getDigest() {
		return CtpJNI.CThostFtdcRspQueryTradeResultBySerialField_Digest_get(
				swigCPtr, this);
	}

	public CThostFtdcRspQueryTradeResultBySerialField() {
		this(CtpJNI.new_CThostFtdcRspQueryTradeResultBySerialField(), true);
	}

}
